### ISSUE TITLE
Research tooling

### ISSUE THREAD

**Issue by skade** [rust-community/team#10]
There might be some tools to assist us in making our work better, especially for visualising processed and importance of recent events.

Rule of thumb:
* no maintenance
* high benefit
* easy access management
* low learning curve

**Comment by aturon** [comment]
One more bullet: orient the whole thing to encourage follow-through.

**Comment by skade** [comment]
I'm creating a few test repositories for that so that I don't move things around here too much.

**Comment by skade** [comment]
https://www.zenhub.io/ is service that works through a plugin for Firefox and Chrome and annotates the issue view.

It takes over the Github interface and adds further elements. Compare:

<img width="614" alt="screen shot 2016-03-24 at 14 45 12" src="https://cloud.githubusercontent.com/assets/47542/14018634/0e0cddd2-f1cf-11e5-9cea-52fc5536944a.png">
<img width="594" alt="screen shot 2016-03-24 at 14 45 05" src="https://cloud.githubusercontent.com/assets/47542/14018635/0e0e02b6-f1cf-11e5-8661-4887a5004d4f.png">

It provides a simple Kanban board on top of the current GH interface and doesn't touch the issues at all (adds no labels, etc.).

Pros:
* Nice integration within the GH interface
* Easy to pick up, not a lot of fluff

Cons:
* Plugin that takes over your _whole_ GH experience (subtle, but still) and looks a bit messy
* People without the plugin miss out all of the status info

My recommendation: pass. It's cool for closed circles, not for open projects.

**Comment by erickt** [comment]
Yeah those cons are a bit sad. I also saw you created a waffle test repo. How did that look?

@aturon also mentioned https://wekan.io in the meeting.

**Comment by aturon** [comment]
> @aturon also mentioned https://wekan.io in the meeting.

Yes, but note that it's just a standalone kanban-style board -- no github integration.

**Comment by frewsxcv** [comment]
I've used https://github.com/huboard/huboard which uses GitHub Issues as the backend. I can recommend it (though I haven't used it for a year or so, so it might have changed)

**Comment by frewsxcv** [comment]
....and yes, it's possible for them to be public:

https://huboard.com/frewsxcv/afl.rs/

Usage is free for open source projects.

**Comment by skade** [comment]
Waffle is nice, but barebones.

It maps issues to a board and tags them by their current column. You can follow the discussion on the board and assign people from there. Columns are configurable.

Pros:

*  Direct mapping to GH
*  Easy to set up, not a lot of fluff, easy to get rid off

Cons:

* Secondary interface
* Most futher integrations don't seem too worthwhile

Verdict: consider

**Comment by skade** [comment]
Huboard is _almost_ the same as Waffle. I find the interface snappier and it allows for milestones to be set. I don't see us using milestones, though ;).

Verdict: consider

**Comment by skade** [comment]
Ubersicht [see our org here](http://espy.github.io/ubersicht/?showOpen=true&showClosed=true&showCommented=true&showUncommented=true&showIssues=true&showPullRequests=true&last24Hours=false&repos=null&labels=null&milestones=null&usernames=null#rust-community) is something I evaluated for Rust in general a while ago. It currently does have a 500 issues limit though, which makes it unusable for extremely large orgs.

It's not a kanban-board and does not track progress, but it's great to get a quick overview, especially if you use multiple repositories.

Pros:
* very good at getting a quick glance to see what is currently actively moved
* Easy to set up (you don't even need to login)
* No secondary _editing_ interface. Once you clicked through, it's the usual GH stuff.
* Cross-Repos view

Cons:
* Secondary interface outside of GH that you have to navigate to
* There's really not much more, editing happens

**Comment by skade** [comment]
Finally: wekan and Trello. OSS and all, I would probably choose wekan :). They are both simple, yet configurable kanban-boards, but have no link to GH issues. That means they are outside of the scope of this repos, which can be a good and a bad thing.

**Comment by skade** [comment]
So, any strong opinions? First of all, give me a hands up whether you want something additional or not (use the reactions feature for that)

**Comment by skade** [comment]
I'll close this for now, although I still see the need for a distributed todo list :)
