### ISSUE TITLE
Page for novemb.rs code sprint

### ISSUE THREAD

**Issue by skade** [rust-community/team#101]
We need a small landing page and a way to submit work packages. I suggest using a separate repository and issue templates for that.

**Comment by badboy** [comment]
Repo: https://github.com/rust-community/european-code-sprint

**Comment by skade** [comment]
By the way, anyone got a good name for this? Prime-meridian code sprint?

**Comment by johannhof** [comment]
Sounds cool but I wouldn't get it :sweat_smile:

**Comment by skade** [comment]
Any other ideas? :)

**Comment by johannhof** [comment]
Not really, maybe we can just explain it on the page

**Comment by skade** [comment]
How about Novembe.rs?

**Comment by skade** [comment]
I'd prefer Novemb.rs on second thought.

**Comment by skade** [comment]
Page is here: https://github.com/rust-community/novemb.rs
