### ISSUE TITLE
Who has a Rust tablecloth

### ISSUE THREAD

**Issue by carols10cents** [rust-community/team#103]
Whoever is assigned to this issue currently has a Rust tablecloth. If you need it for an event, ask them!

**Comment by erickt** [comment]
@skade / @johannhof: do you also have the one we sent over to Europe?

**Comment by johannhof** [comment]
We could order one for every Mozilla office, really. Distribute them a bit more. How do you order these things?

**Comment by johannhof** [comment]
> do you also have the one we sent over to Europe?

Nope, I don't know where it is :/ @skade maybe?

**Comment by erickt** [comment]
@johannhof: I believe @wifelette had them made.

**Comment by skade** [comment]
@johannhof It's in the asquera office, together with the rest of the Mozilla stuff.

**Comment by wifelette** [comment]
Indeed, @cgoostree and I had them printed :) They were about $240 USD each, though we had them made last minute so we paid for rush production and shipping too. It's possible with more lead time there's a cheaper similar option that takes longer to produce, should be easy to investigate if more are needed.

We sent one to Philly and one to Europe post RustConf, sounds like both are accounted for!

**Comment by skade** [comment]
I think this can be closed, the cloths are accounted for.

**Comment by carols10cents** [comment]
Actually I meant for this to stay open forever so that people know who to
ask for the tablecloth when they need it.

**Comment by skade** [comment]
In that case, wouldn't it be better to run an inventory somewhere?
