### ISSUE TITLE
2016-11-02 Community Team Meeting

### ISSUE THREAD

**Issue by frewsxcv** [rust-community/team#104]
Last week's agenda: https://github.com/rust-community/team/issues/102
- [ ] Involvement with 24 Pull Requests this year: http://24pullrequests.com/ (cc @carols10cents)
- [ ] [Rust project conferences RFC by skade](https://github.com/skade/rfcs/blob/rust-conferences/text/0000-rust-project-conferences.md) – @badboy: I briefly talked to Aaron at RBR. He wants to talk to all current organisators about the future of Rust conferences eventually.
- [ ] [novemb.rs](https://github.com/rust-community/team/issues/95)

**Comment by jonathandturner** [comment]
- [ ] Commercial user survey update

**Comment by edunham** [comment]
support/speakers for international Rust groups

**Comment by jonathandturner** [comment]
- [ ] quick heads-up re: GNOME

**Comment by erickt** [comment]
Action Items:
* need to get comments to @skade on the RFC this week
* need to get comments back to @jonathandturner on the commercial survey by Thursday
* @carols10cents will register [LfC projects with 24pullrequests](https://github.com/rust-community/team/issues/105)
* @edunham will work with @skade and @johannhof on getting them stickers for novemb.rs
* @edunham will do a rough summary of https://github.com/rust-community/team/issues/4 on a website.
* @skade and @carols10cents will start working on [conference post mortems](https://github.com/rust-community/team/issues/108)
