### ISSUE TITLE
Conference Retrospectives

### ISSUE THREAD

**Issue by erickt** [rust-community/team#108]
Now that the conferences are over, we'd like to do a retrospective writeup about them for future conference organizers and the broader public.

* [x] @aturon (or whomever you nominate): rustconf
* [x] @skade / @johannhof: rustfest
* [x] @carols10cents: RBR

We are aiming to have this done by early december so the RBR survey results are in. We'd like to also plan a meeting with the core team to go over the results, and then publish them afterwards.

**Comment by carols10cents** [comment]
Proposal/assumptions made during the community team meeting:

- Each conf writes up something before the synchronous meeting
- Presumably we read each others' writeups before the synchronous meeting
- The meeting will be a vidyo/hangout
- The purpose of the meeting is to discuss any issues that need to be discussed from the writeups and brainstorm how to address issues for the 2017 conferences
- We should make an agenda before having this call
- Call will be scheduled for no longer than an hour

**Comment by carols10cents** [comment]
Assuming that us organizers have a week from today to complete our writeups, the meeting won't be before Dec 7.

I can probably be available most weekdays in December between 14:00 UTC and 22:00 UTC. #freelancelife

**Comment by aturon** [comment]
Note that Mozilla folks are all traveling week of Dec 5th. The week after should be fine.

Can someone elaborate a bit on what should go in the writeup?

**Comment by carols10cents** [comment]
> Can someone elaborate a bit on what should go in the writeup?

I'm thinking:

- Things that worked/went well
- Things that didn't work/go well
- Improvements to be made for future years

Things the conferences could learn from each others' successes/mistakes, basically?

@skade wdyt?

**Comment by erickt** [comment]
@carols10cents / @aturon / @skade: how is next week looking for you all? Lets say Tuesday at 9am PST?

**Comment by carols10cents** [comment]
Works for me!

**Comment by erickt** [comment]
@badboy said this time would work for him, and he'd try to wrangle the other rustfest folks into getting some things written down before the meeting.

**Comment by badboy** [comment]
9am PST = 6pm CET

**Comment by aturon** [comment]
Fine for me!

**Comment by skade** [comment]
I'm fine with that.

**Comment by Hoverbear** [comment]
I'm in for this =D

**Comment by flaki** [comment]
Gonna try and drop by too.

**Comment by johannhof** [comment]
I'm still on PTO :)

**Comment by aturon** [comment]
Note: the invite has been updated to half an hour later, at 9:30AM PST = 6:30 PM CET

**Comment by carols10cents** [comment]
Whew, finished my writeup! https://oasis.sandstorm.io/shared/TY10D1hasr7BXCLnrOlA8inn0dCU_Drc38aLB8fTtof

**Comment by aturon** [comment]
Here's the RustConf writeup: https://gist.github.com/aturon/9dea2c81f24959ed8822e432edaeef4c

**Comment by skade** [comment]
Here's the RustFest writeup: https://gist.github.com/skade/722dc70432a6e471410016988c5a676f

There's a team only addendum I'll send around later.

**Comment by carols10cents** [comment]
Are we using the hangout link that's in the invite?

**Comment by Hoverbear** [comment]
I see no hangout link!

**Comment by badboy** [comment]
@Hoverbear You weren't in the initial email invite. I can send you the link later.

**Comment by Hoverbear** [comment]
I got one!

**Comment by Manishearth** [comment]
i have an invite but it doesn't have a hangouts link O.o

**Comment by carols10cents** [comment]
@Manishearth PMed what I have to you on IRC :)

**Comment by Hoverbear** [comment]
Are you all late or am I in the wrong meeting?

**Comment by aturon** [comment]
@Hoverbear The meeting [was moved back by half an hour](https://github.com/rust-community/team/issues/108#issuecomment-268035314)

**Comment by aturon** [comment]
Etherpad here: https://public.etherpad-mozilla.org/p/rust-2016-conf-retrospective

**Comment by erickt** [comment]
@carols10cents's retrospective in a more permanent form: https://gist.github.com/erickt/300d82eda262c70f144271c33c46c666

**Comment by erickt** [comment]
We had our meeting and conference planning has begun!
