### ISSUE TITLE
Easy, approachable workshop topics

### ISSUE THREAD

**Issue by skade** [rust-community/team#11]
Find easy, approachable tutorial topics.

* Must work on Rust stable
* Can involve additional hardware
* People must have something usable in a workshop day
* assume zero previous experience

**Comment by ligthyear** [comment]
We've had very good experience with using the Logo-[Turtle approach](https://en.wikipedia.org/wiki/Turtle_graphics) for the [OpenTechSchool Python Materials](http://opentechschool.github.io/python-beginners/). In case you don't know turtle: it basically opens a blank window with a small turtle in the middle and you can programmatically make that turtle move around (and turn, change color and alike). With every move it draws a line. Very visual, highly engaging and surprising how many (creative) challenges you can make with such a simple setting.

So, I did some research and found this cool [Rurtle lib](https://github.com/Kingdread/Rurtle), an implementation of turtle in rust – it even has a Ferris as the primary icon:

![screen shot 2016-03-28 at 19 20 25](https://cloud.githubusercontent.com/assets/40496/14148585/54757452-f6a0-11e5-9725-b3f81feca121.png)


It might not be officially released yet and primarily focuses on an interactive shell of the turtle language, but it can easily be used from rust instead. Taking the OTS python material as an inspiration and adapting the content to use rust and rurtle is a promising approach!

----

Disclaimer: the library uses piston, which – as far as I understand – needs the freetype-lib-headers as a system dependency at the moment. Which might be tricky to get working on a not-for-development-configured Windows. But there is quite some urge to get rid of that dependency from the piston devs.

**Comment by booyaa** [comment]
How about a workshop involving robots? I haven't found a dedicated crate, but someone's got repo that allow interaction with an arduino. https://github.com/jensnockert/dueboot I also found this deck explaining why rust and physical computing could be a good fit: http://www.slideshare.net/kellogh/glue-con14

The nodebots have a proven track record in enabling people to create robots by learning javascript: http://nodebots.io Perhaps something similar could be achieved with Rust?

**Comment by aturon** [comment]
@booyaa I love that idea -- it's a great fit for Rust. I think that @brson has been thinking about some things along those lines.

One downside I see is that it could increase workshop costs a bit, since you need the hardware.

**Comment by sbeckeriv** [comment]
Hello,

How about image filters? Its visual in a sense, easy to tweak, as a few levels of progression and really only needs the image crate from piston. You can start with a simple grayscale pixel by pixel  and move to more of a matrix filter which does edge detection.

I started on a project like this after a seattle meetup https://github.com/sbeckeriv/color-filters I have lost focus but it was fun and visual. All of my example outs are uploaded to s3 as well. I linked them here if you want to see them https://gist.github.com/sbeckeriv/9f670968d43f0af70f6e4e9bbbc37beb 

Either way excited to see where this project goes. I have heard people at the ruby meetup are exploring rust and a training day might go far.

**Comment by skade** [comment]
I'll close this, this is a core topic of rustbridge.
