### ISSUE TITLE
Make Rust YouTube Channel videos available for translation on Amara

### ISSUE THREAD

**Issue by sebasmagri** [rust-community/team#118]
Hi!

Great work guys,

I wonder if it would be possible to have an [Amara](https://amara.org) team to coordinate the translation of subtitles for videos in the YouTube channel to other languages.

Mozilla has used Amara for long time for mozillians to translate videos and I believe it has been a successful experience.

Amara supports importing videos directly from YouTube, as well as uploading subtitles. It does have an API as well but I can't still find its docs.

I'm willing to help with this if it's needed.

Regards,

**Comment by skade** [comment]
We will be included in the Mozilla org as a subteam on this weekend.

It seems like there is a little import problem: only videos on our channel are included on amara, that does exclude our RustConf ones. /cc @aturon @wifelette

**Comment by skade** [comment]
We have a team set up, but the rustconf and rust belt rust videos are not available, as they opted for having a separate channel :(.

/cc @carols10cents

**Comment by aturon** [comment]
I can talk to Leah about whether we can also upload on the main channel at this point (she's currently on maternity leave).

**Comment by cgoostree** [comment]
I've received the RustConf videos. Where/how should they go? They'll still be on Confreaks channel/site, but we’ve worked it out so it’s fine to post in multiple places.

**Comment by skade** [comment]
@cgoostree Someone needs to invite you to our youtube group. (I'm on slow internet currently, but @badboy for example should be able to do it)

**Comment by badboy** [comment]
I just need a mail to invite you

**Comment by cgoostree** [comment]
crystal@tilde.io

**Comment by badboy** [comment]
You should have an invitation now

**Comment by sebasmagri** [comment]
Is there anything missing on this regard? We're planning a translate-athon in Mexico City for this after our RustFest.

**Comment by skade** [comment]
It is available for translation, but no one is doing it. I'd be happy if that changed, but that should be another topic.

Hopefully #178 can move things here.
