### ISSUE TITLE
Investigate possibility of Mozilla streaming a 24 hour remote rust conf

### ISSUE THREAD

**Issue by carols10cents** [rust-community/team#123]
Whether the tech and people needed to run this would willing and able!

**Comment by booyaa** [comment]
I'd like to volunteer myself for the London time slot (assume we go 24 hours) does it have to been a Mozilla office or could we use alternative venues provided they can stream?

**Comment by aturon** [comment]
@booyaa the only requirement is hooking in via Vidyo, the video conferencing software we use, which is free to download.

**Comment by Manishearth** [comment]
It's a bit tricky to use Vidyo as a nonemployee though. Might be possible to grant temp LDAP or something. Or rope in a nearby interested employee. idk.

**Comment by erickt** [comment]
We could also try [Youtube Live](https://www.youtube.com/channel/UC4R8DWoMoI7CAwX8_LjQHig), which might be easier to get setup around the world.

**Comment by erickt** [comment]
Especially since we might have locations that don't have a convenient local Mozilla employee.

**Comment by Manishearth** [comment]
With Vidyo you can have multiroom streaming though, with multiple people on multiple podiums in a single picture.

All of this can stream on airmo.

**Comment by Manishearth** [comment]
Occurs to me that the SF meetup already uses vidyo for non-employees giving remote talks. so this should still work!

**Comment by carols10cents** [comment]
Closing as a dupe of #136, unless there's some distinction i'm missing...
