### ISSUE TITLE
More advertisement for underhanded.rs

### ISSUE THREAD

**Issue by booyaa** [rust-community/team#127]
- [x] twir (@erickt?)
- [ ] podcasts (even just an announcement, but may get asked for an interview)
   - [x] The New Rustacean - awaiting response
   - [x] Software Daily - awaiting response
   - [ ] The changelog
- [ ] meetups
  - [x] February London (@booyaa)
  - [ ] March SF (cc @Manishearth)
  - [ ] Cologne (cc @badboy)
  - [ ] Berlin (Hack & Learn) (cc @johannhof)

**Comment by skade** [comment]
Berlin Hack & Learn is currently better served by @johannhof

**Comment by skade** [comment]
underhanded.rs is over.
