### ISSUE TITLE
2017 commercial survey planning

### ISSUE THREAD

**Issue by erickt** [rust-community/team#128]
Like #28, this is a ticket for tracking things we want to do in the next [commercial survey](https://internals.rust-lang.org/t/2016-rust-commercial-user-survey-results/4317).

* We should ask users what crates they're using to help us figure out what people consider what is production ready.

**Comment by skade** [comment]
@erickt Could you note down the status of that?

**Comment by ashleygwilliams** [comment]
as 2017 is basically over, i am going to close this issue. @bstrie has created an issue for 2018 already.
