### ISSUE TITLE
2016-03-30 Meeting

### ISSUE THREAD

**Issue by erickt** [rust-community/team#13]
Meeting at 5pm UTC. Check this [link](http://everytimezone.com/#2016-3-29,1740,cn3) for your local timezone.

Agenda items:

* Welcome @carols10cents!
* Rescheduling next meeting to 4pm UTC [local timezone](http://everytimezone.com/#2016-3-29,1680,cn3)?
* Buy off from everyone about using Vidyo / Skype / Hangouts for next meeting.
* How can we help support the upcoming conferences?
 * [OSCON](http://conferences.oreilly.com/oscon/open-source-us) Talks: [Steve](http://conferences.oreilly.com/oscon/open-source-us/public/schedule/detail/49862), [Emily](http://conferences.oreilly.com/oscon/open-source-us/public/schedule/detail/49024), [bstrie](http://conferences.oreilly.com/oscon/open-source-us/public/schedule/detail/49932)
 * [Rust Belt](http://www.rust-belt-rust.com/)
 * European Conference (is there a website?)
 * RustCamp / RustCon
* [Tooling Update](https://github.com/rust-community/team/issues/10)
* [Switchboard Update](https://github.com/rust-community/team/issues/12)
* [Blog Post volunteer?](https://github.com/rust-community/team/issues/8)
* [A number of items from @aturon's and core team's perspective](https://github.com/rust-community/team/issues/3#issuecomment-200426802)

Anyone else have anything they want to add for the meeting?

**Comment by erickt** [comment]
For ease of setting up, lets have another irc meeting again tomorrow at 10am PST. See http://everytimezone.com/#2016-3-29,1740,cn3 or the community calendar to see when the meeting is in your timezone.

**Comment by erickt** [comment]
Link to last week's agenda: https://github.com/rust-community/team/issues/3

**Comment by aturon** [comment]
Here's a link specifically to some of the most important items from my (and I think the broader core team's) perspective: https://github.com/rust-community/team/issues/3#issuecomment-200426802

**Comment by erickt** [comment]
* Shifted meeting to 4pm UTC.
* Monthly VTC meeting, hangouts meeting next week 
* Need to gather more info on OSCON Contribute / outreach for tutorials
* @carols10cents is okay right now on RustBeltRust, but is interested in help finding key note speakers. Will sync with @aturon about Rust{Camp,Con}.
* Start a rust community blog.
