### ISSUE TITLE
Closed Category for Tech Speakers on URLO

### ISSUE THREAD

**Issue by skade** [rust-community/team#130]
Hi,

we discussed setting up an internal Discourse for speakers and mentors for RustFest, to allow more focused discussion of proposals and requesting feedback to a talk.

Ben suggested that we could just put this on URLO as a hidden and invite-only category, seeded with past and future speakers at our conferences. This allows us to keep this as an ongoing project and avoids building another RustFest silo.

The rules around this are a bit fuzzy, especially when to invite people (preferably some way to join before writing a proposal), but this can later be clearly fleshed out. It makes sense to keep this hidden, as there is still some discomfort about openly working on talks and proposals. I'm not fully sure about "invite only".

We'd like to do this rather soon, as next RustFest is April 30th.

Best,
Florian

**Comment by badboy** [comment]
No rejection of the idea, though some things were left unclear.

* Only RustFest? Or could this be re-used by other confs after that?
* Is this also to (openly) discuss proposal ideas before submitting?
* Naming it "proposal workshop" or "future speakers" was favored instead of "Speakers space"

**Comment by skade** [comment]
Its meant to be an offer to any community projects, including meetups and all other conferences that may want to join.

Discussing proposal ideas is also perfectly fine. It might be a problem for the conferences with hidden submissions.

Name: combine both and call it the "talk workshop"?

**Comment by skade** [comment]
Up here, currently with a short introduction:

https://users.rust-lang.org/t/get-help-with-with-your-talk-in-all-stages/9642

Can someone try to ask for an invite?

**Comment by badboy** [comment]
I'm not sure how an invite can be requested/must be requested.
I can see that topic and can select the category

**Comment by skade** [comment]
@badboy I already added you.

**Comment by badboy** [comment]
Oh :D that explains things

**Comment by skade** [comment]
We have it.

**Comment by vigneshwerd** [comment]
@skade I can't see the topic in URLO it's probably because I am not invited. I was wondering if the information about this category and invite criteria is documented in someplace.
