### ISSUE TITLE
Talk to Mozilla about using Vidyo / air.mozilla.org for conference

### ISSUE THREAD

**Issue by erickt** [rust-community/team#136]
We could stream from the Mozilla offices, but we would need to coordinate with Mozilla to see if it would be possible to get this setup worldwide, especially if we try to do this over 24 hours.

**Comment by Manishearth** [comment]
The tricky bit with doing it over 24 hours is that the folks coordinating the AV will need to be around for that long (in shifts perhaps), so it's not a trivial ask. They might be able to give us enough control to run it ourselves, idk. I certainly don't mind camping out in the SF office for as long as I can stay awake and coordinating this.

**Comment by carols10cents** [comment]
@Manishearth we're currently thinking September. could you get a definite yes or no from the Moz A/V folks, and if they're in, see if there's a date in September that would be better or worse?

**Comment by erickt** [comment]
@Manishearth and also check in other major mozilla offices, like Paris and Berlin. Are there also offices in Sao Paolo and Beijing? We could try to see if those spaces are available as well.

**Comment by Manishearth** [comment]
I'm travelling for most of this month, can't really do this now.

We can get a yes for doing it without AV ops folks, it's having someone man the controls which is hard.

**Comment by skade** [comment]
I'm in Paris next month, if someone puts me in touch, I could have a little chat.

**Comment by skade** [comment]
Both services are closed now :)

**Comment by skade** [comment]
Both services are closed now :)
