### ISSUE TITLE
1.0 anniversary

### ISSUE THREAD

**Issue by nrc** [rust-community/team#14]
The 1.0 anniversary will be on May 15th (I think, probably good idea to check that). It's a great opportunity to do some celebration/reflection/engagement, especially since there are no plans for 2.0.

There are some plans in the works for blog posts, etc. It might also be nice to mark the event with coordinated meetups or something to make it more of a community celebration and less of an announcement.

Any ideas?

**Comment by aturon** [comment]
Note that the core team has significant plans around the official blog in the near future, and will be taking the 1.0 anniversary into account here. I'll communicate more details about that soon.

The community team effort should focus on broader efforts as @nrc is suggesting here. Coordinated meetups a la the 1.0 launch parties could be fun!

**Comment by skade** [comment]
I'm not sure about how important that is in the US, but the 15th is Whit sunday this year.

It might be worthwhile to shift by a little.
