### ISSUE TITLE
Meeting times

### ISSUE THREAD

**Issue by badboy** [rust-community/team#146]
Current time: 5pm UTC

https://www.worldtimebuddy.com/?qm=1&lid=2656046,2179537,5128581,5391959&h=2656046&date=2017-3-13&sln=17-18

US already jumped ahead with their clock, Europe and other parts will follow soon.

We might need to re-evaluate the time of the meeting

**Comment by erickt** [comment]
Good idea. I'm fine shifting to 4pm UTC if that works for everyone until this daylight savings time mess resolves itself.

**Comment by edunham** [comment]
I made a thing (https://github.com/rust-community/team/wiki/Meeting-Availability) and emailed the list about it to try to solve the general case of this problem.

**Comment by skade** [comment]
@rust-community/community-team Is this still a topic of debate?

Otherwise, I'll close.

**Comment by ashleygwilliams** [comment]
this appears to be stale but i'll bring it up in the next meeting to see if we need to do anything

**Comment by Manishearth** [comment]
I'm going to be in GMT+5:30 till February. Current times kind of work for the first meeting.

**Comment by ashleygwilliams** [comment]
@Manishearth is there a better time for you? attendance at the second meeting is much lower so its possible that we could move it

**Comment by Manishearth** [comment]
So I'll mention this at the outset that as far as meeting scheduling is concerned, there's going to be at least one band of timezones that gets the short straw. India usually ends up here, being almost 12 hours off from PST. So I'm largely used to this and can probably make it still work by pre/post/async communicating provided we have agendas set (which we do!). So we shouldn't have to worry about this much.

That said, if the late meeting was four hours later that would work for me. It would suck for EST though :)

The morning (morning PST) meeting is attendable for me so I don't think we need to change anything here.

**Comment by ashleygwilliams** [comment]
👍 i'm going to close this for the moment then. thanks for the thoughtful response @Manishearth
