### ISSUE TITLE
2017-03-22 Community team meeting

### ISSUE THREAD

**Issue by erickt** [rust-community/team#148]
Meeting at **5pm UTC** on #rust-community on irc.mozilla.org

Last week's agenda: #147

This week's agenda:

* Last chance for underhanded buzz
* RustFest buzz

EIAL (Easy IRC Access Link): https://kiwiirc.com/client/irc.mozilla.org:+6667/#rust-community

**Comment by edunham** [comment]
Action items: 

- [ ] r/rust mods sticky an underhanded thread shortly before the deadline
- [ ] everybody tweet about 2017.rustfest.eu/#tickets


Feedback on how underhanded could be improved. 
* Longer submission period 
*  fewer submission completeness requirements (ie, just submit ideas for publication for others to test) could help
* Matchmaking between people with ideas / mentorship and those with time to implement
