### ISSUE TITLE
Birthday party organization

### ISSUE THREAD

**Issue by erickt** [rust-community/team#151]
Rust's birthday is on May 15th, so we should party:

- [ ] organize blog post
- [x] recruit meetups to organize birthday parties
- [x] get stickers printed up
- [x] mail stickers to community events

What else do we need to do?

**Comment by edunham** [comment]
- [ ] Get mailing addresses and requested sticker counts from interested community events

**Comment by Manishearth** [comment]
I can start the blog posts if folks are okay with that. Will probably be better if a bunch of us collab on the content.

**Comment by erickt** [comment]
@Manishearth sure. @aturon wrote [last years](https://blog.rust-lang.org/2016/05/16/rust-at-one-year.html), so you could probably use that as a template.

**Comment by colin-kiegel** [comment]
FYI The Cologne meetup is planning to stretch the birthday celebration over two meetups on May 5th and June 6th (as last year). [This is our planning discussion](https://github.com/Rustaceans/rust-cologne/issues/26).

**Comment by dns2utf8** [comment]
I added an entry to the communtiy calendar.

**Comment by bitshifter** [comment]
Sydney is planning a meetup on May 15th. Seemed like as good a day as any for our somewhat irregular meetings :)

**Comment by dns2utf8** [comment]
![rust-logo-blk_2-year-aniversary](https://cloud.githubusercontent.com/assets/739070/25554754/bd65ea66-2cd5-11e7-87c5-8b08b5d54c5d.png)
I made that logo for our [meetup](https://www.meetup.com/de-DE/Rust-Zurich/events/239152044/), you can use it if you like.

**Comment by edunham** [comment]
@dns2utf8 Thanks for the art! Unfortunately I had already slapped together a design and sent it off to printing just a couple days before you shared this. 

Stickers of the Rust logo on an orange balloon (they ended up looking a bit like Bors's avatar, but oh well) are currently in the mail to all the meetups which requested them.

**Comment by skade** [comment]
Birthday is over.
