### ISSUE TITLE
2017 Community Survey

### ISSUE THREAD

**Issue by erickt** [rust-community/team#153]
It's about time to start organizing the 2017 Community Survey. I'll start the template based on last year's questions. Don't forget to check out https://github.com/rust-community/team/issues/28, which has some changes we wanted to make for this survey.

**Comment by skade** [comment]
We should use a different survey tool. Google Forms has many bad things that make processing of the data later painful. For example it saves all answers in text form (not as a reference to their option number). This means making small changes (like fixing a typo) makes it hard to find the answer later. Also, if you have multiple options + a free form field, all will be pushed into one field. It doesn't escape special characters, making the CSV download unusable. It comma-separates within the fields and doesn't escape commas in free-form or any other answers. The only ways to properly work with this data is by using Googles own tool or do _a lot of scrubbing_.

It also doesn't allow you to download the structure of the survey to derive the analysis from there. 

I'm not sure, which the best alternatives are. I know of typeform and surveymonkey, but both I have only used when filling out.

**Comment by erickt** [comment]
We launched! Moving feedback on the 2017 survey to #160.

**Comment by skade** [comment]
Closing this, as this is the tracking issue for _running_ the survey.
