### ISSUE TITLE
blog.community.rs

### ISSUE THREAD

**Issue by erickt** [rust-community/team#154]
As of right now, the core team is trying to reserve blog.rust-lang.org for just major events in the language and the community. We haven't yet figured out proper standards for guest blogging. On the community side though, we could set up our own blogging site that sets out to be open to guest posting.

**Comment by skade** [comment]
Probably just having different venues and encouraging more people to guest post about their events makes sense anyways. Should we just copy the setup from blog.rust-lang.org?

I have some content already, for at least 2 blog posts.

**Comment by skade** [comment]
https://github.com/rust-community/blog.community.rs

**Comment by skade** [comment]
Closing this, as this now exists. Please reopen if there is something else to discuss here.
