### ISSUE TITLE
2017-05-10 community team meeting

### ISSUE THREAD

**Issue by Manishearth** [rust-community/team#161]
TWO Meetings, at [4-4:30pm UTC](http://everytimezone.com/#2017-5-10,240,cn3) and [10-10:30pm UTC](http://everytimezone.com/#2017-5-10,600,cn3) on #rust-community on irc.mozilla.org

Last week's agenda: #159 

This week's agenda:

 - https://github.com/kud1ing/awesome-rust/issues/289#issuecomment-299945867 (@manishearth and @booyaa )
- underhanded update
- worldwide conference
- website

**Comment by thejpster** [comment]
New meetup in Cambridge (UK) @ https://www.meetup.com/Cambridge-Rust-Meetup/. Guests and speakers actively sought.
