### ISSUE TITLE
New Group

### ISSUE THREAD

**Issue by gsquire** [rust-community/team#163]
I'm not entirely sure if this is the right place to ask, but I recently started a new [Rust group](https://www.meetup.com/oc-rust/) for Orange County, California. I wanted to see how I can improve the page to make sure it's like the other groups and that people who are interested can find it.

**Comment by badboy** [comment]
Hey, you reached the right folks.
Great to see another meetup pop up.

To make your approach more known advertise it on the several Rust mediums we have:

1. Post it on http://users.rust-lang.org/
2. Post it on https://www.reddit.com/r/rust/
3. Once you have a date & location, let us know and we'll add it to the Community Calendar and it will pop up in [This Week in Rust](https://this-week-in-rust.org/) as well

Depending on what you have in mind for this meetup, reach out to potential speakers to talk about Rust at the meetup

**Comment by gsquire** [comment]
Ok, I posted to Reddit. I am working with my company to find a room to host for now. I will set a date in the future for the first meeting.

Thanks for your time.
