### ISSUE TITLE
Create subdomains for cfp.community.rs and herald.community.rs

### ISSUE THREAD

**Issue by erickt** [rust-community/team#172]
We're thinking about putting @skade's cfp and herald app under the community.rs domain name.

**Comment by edunham** [comment]
Links to the apps?

**Comment by skade** [comment]
https://status.yakshav.es

https://cfp.yakshav.es (For the latter, please ask for an invitation, with no CFPs open, there's not much to see)

**Comment by skade** [comment]
If you point a CNAME at herald.community.rs.herokudns.com, I can change the OAuth apps later.

**Comment by erickt** [comment]
@skade: https://herald.community.rs is live!

**Comment by skade** [comment]
Closing.
