### ISSUE TITLE
ANN: First South African Rust meetup

### ISSUE THREAD

**Issue by stephanbuys** [rust-community/team#180]
Hi all,

Just wanted to bring this event (and group) to your attention:
https://www.meetup.com/Johannesburg-Rust-Meetup/events/241977391/

Cheers,
Stephan

**Comment by skade** [comment]
Hi Stephan,

great! I'm glad to see that! I think I have you email, do you mind if I add you to the community calendar editors?

(Finally, I may be passing ZA by next year, so please keep it up :))

Best,
Florian

**Comment by stephanbuys** [comment]
Hi Florian,

Please go ahead. Please do be in touch when you're in town!

Cheers,
Stephan

**Comment by stephanbuys** [comment]
Any suggestions/guidelines for good first meetup topics?

**Comment by vigneshwerd** [comment]
Hi @stephanbuys ,

Check out the resources at [Rust India community](github.com/MozillaIndia/RustIndia) repo. 

If it's a full day meet up I would suggest the following activities: 

* Setup the Rust compiler
   * Understand the different functionalities of Rustup tool
   * Understand the release process, different tier of platforms supported etc
   * See who is using Rust

* Hand's on Rust programming
   * Getting a feel of the type system
   * Borrowing and ownership concept
   * Get familiar with struct, impl, trait, modules, and crate concepts

* Explore Cargo and commands
   * Create a project, write test cases, bench mark the project 
   * Package projects

* Try out the recipes and build some cool projects:
   * Try out the Rayon crate
   * Creating a high-performance python module using Rust
   * Web development in Rust
   * Try out the recipes in this [cookbook](brson.github.io/rust-cookbook)

* Talk about contribution areas:
   * [Libz Blitz](https://blog.rust-lang.org/2017/05/05/libz-blitz.html)
   * [Rust Api guidelines](https://github.com/brson/rust-api-guidelines)

All the above materials are available in the Rust India repo, feel free to hack on it and submit PR in case you have something new to add.

I just shortly composed this agenda list,  feel free to modify it.

Best of luck with your South African Rust meetup event :)

**Comment by skade** [comment]
@stephanbuys I added the date to the calendar and added you with the rights to enter your own events.

Also, on you first meetup, it's perfectly fine to just have people meeting and figure out what they are interested in.

**Comment by skade** [comment]
@stephanbuys Also, please close this issue once you feel all your questions are answered for the time being :).

**Comment by stephanbuys** [comment]
@skade thanks!

**Comment by vigneshwerd** [comment]
@skade can you give me access to the Rust calendar so that I can also add the events happening in the Indian region.

**Comment by skade** [comment]
@vigneshwerd Please open a seperate issue for that. I nearly missed that one :).

Can you please send an email to community-team@rust-lang.org mentioning the email of your Google account, I'll add you :).

**Comment by vigneshwerd** [comment]
@skade Done :) 

Thanks for the support.
