### ISSUE TITLE
FOSDEM 2018 devroom

### ISSUE THREAD

**Issue by ehiggs** [rust-community/team#187]
Hi,
I've organized a Rust BoF at FOSDEM 2016 and 2017. At the 2017 BoF I counted ~80 people in attendance. I polled the group and everyone wanted a devroom in 2018. So I'm preparing a proposal to submit as soon as the [call for devrooms opens up](https://fosdem.org) along with some people who approached me in February offering to help (@itkovian, @lucab; @joshtriplett also offered to help but isn't sure if he'll be able to make it to the event).

I think we have [a good proposal](https://docs.google.com/document/d/16lz4CNOiCXz0hhJpNlN9sNaopqlVFPkLWIllm0EosqA/edit?usp=sharing) but I'd love for someone in the community team had a look. If someone in the community team wants to get involved, that's a discussion we can have too.

**Comment by mre** [comment]
Would also offer my help.

**Comment by vigneshwerd** [comment]
@ehiggs well-written proposal. Consider adding Rust FFI topic in the proposal which enables developers to build extensions in their current applications using Rust.

**Comment by ehiggs** [comment]
@vigneshwerd, done. Thanks for the feedback.

**Comment by Grummfy** [comment]
the proposal is nice. I think a lot of people would be intrested.
How do you plan to choose the speaker? it could be interesting to perhaps launch en opencfp instance for it?

**Comment by skade** [comment]
FOSDEM has their own CFP system that they wish you to use.

**Comment by Grummfy** [comment]
oh, I was not aware of it. Most of the time the I submit talk is for the php room, and it's not with the one from fosdem ;)

**Comment by ehiggs** [comment]
@Grummfy, the process is as follows:

1. FOSDEM makes a call for parcipation for devrooms. This usually has a deadline in August or early September. 

2. We apply for a devroom with two people on the actual application on penta.fosdem.org.

3. FOSDEM mails the devrooms to let them know the decisions. This might involve merging rooms (e.g. Scheme and Lua were sort-of merged; HPC and Big Data proposals were merged - which was a stroke of genius because it's a big success imo).

4. FOSDEM announces the devrooms publically.

Then, the rest if what we've done in previous years with the HPC+Big Data room:

5. We make a CFP for the devroom ([example for HPC room](https://hpc-bigdata-fosdem17.github.io/)) with a deadline of early december. This is where community people can shine because I don't think getting talk proposals out of people is my forté.

6. We then ask for accounts on penta.fosdem.org to be permissioned for the Rust devroom for everyone who is an organizer and needs to see the talk proposals. i.e. get accounts permissioned for jury-members.

7. Talks show up in penta.fosdem.org and the jury organizes them. What I've done in previous years: Make a google doc spreadsheet shared with jury members. Jury members rate each talk 1-5 within 2 weeks of deadline. If we have a lot of proposals we discuss whether we will have a window of lightning talks to let more people get their messages out. Meet online to discuss the results (e.g. if some people voted 5 and some people voted 2 for a talk we figure out why the high variance). 

8. We contact people who might have had their talks approved to see if they're still able to make it and if we offer a lightning talk; we ask if they're still willing to come to give their talk as a lightning talk. This needs a deadline where people who don't respond get bumped.

9. Hopefully the schedule is done by New Year or early January at the latest.

**Comment by itkovian** [comment]
Deadline is 17 September [2017] according to https://submission.fosdem.org/devroom.php.

**Comment by ehiggs** [comment]
Devroom proposal was submitted.

**Comment by erickt** [comment]
This is a great idea! We talked about it in our team meeting, and while it's super early, we might be able to pull in some representation. @Manishearth and @edunham said they may be able to attend. Also local-ish are @booyaa and @badboy. They might be interested.

**Comment by badboy** [comment]
here! o/ I would do my best to be there if there's a Dev Room (and happy to help with any on-site needs), but given how early it is can't commit 100%.

**Comment by nical** [comment]
Hi! I'll attend FOSDEM and I'll happily help out.

**Comment by ehiggs** [comment]
Hi @nical, @badboy. Thanks for the offer of help.

The proposal has been submitted on 4 September. We're waiting on whether we will get the devroom.  Then we will have a short time frame before we need to offer a call for participation (probably a post on r/rust and users.rust-lang.org as well as a github pages site). This CfP will need to be shopped around to make sure we get plenty of high quality submissions.

On the day we will need people for heralding, working the camera, managing the door (as FOSDEM becomes crowded we will need to prevent overfilling the room) and an extra person on hand to step in (bathroom breaks; runner to collect anything from the video room, lunch). Having more people helps because it lightens the load and lets people wander around and check out talks in other rooms (or even give talks in other rooms).

I think it's too early to plan roles for the room, but knowing who to contact when the time comes is v. helpful.

**Comment by Grummfy** [comment]
it has been accepted : https://fosdem.org/2018/news/2017-10-04-accepted-developer-rooms/

**Comment by skade** [comment]
Congratulations! I wish you a great day!

**Comment by skade** [comment]
Sorry for the double-post: if you need a CFP application, the application behind https://cfp.rustfest.eu is able to handle multiple domains and multiple cfps, we can quickly create one there for you, if you want to.

**Comment by Grummfy** [comment]
there is a lot of cfp app : https://github.com/opencfp/opencfp, https://github.com/rubycentral/cfp-app, ... but has I understood, the fosdem is proposing one.

**Comment by skade** [comment]
My point was that ours is installed, operated and running. It's a slightly modified installation of the rubycentral one.

**Comment by Grummfy** [comment]
oh, nice. In this case, I can point a subname of the rust belgium meetup if it's just a subname.

**Comment by ehiggs** [comment]
Fosdem uses a custom submission management system called penta or pentabarf. Everyone will need to submit their talks at https://penta.fosdem.org but we will release a CfP shortly with guidelines on what to submit.

Ps: I'm loving the enthusiasm here!

**Comment by lucab** [comment]
Just a small update, we are assembling a simple static page with CfP details and link to the FOSDEM submission system here: https://github.com/rust-fosdem/rust-fosdem.github.io.
We are planning to spread this broadly at the end of next week, so feel free to send suggestions/fixes there via PRs before that.

Room allocation will be confirmed soon, but according to latest updates we will be on Sunday Feb 4th with room capacity for ~100 seats.

@nical @badboy et al: we would be happy to have 2 or 3 more people helping organizing, especially there on-site. If you already know you'll be at FOSDEM and willing to help, please add yourself to the ORGANIZERS list in the repo

**Comment by badboy** [comment]
Done!

**Comment by mre** [comment]
@lucab @ehiggs, would you be interested in adding me as an organizer? I'm a member of Rust Cologne like @badboy, so maybe we could join forces here. 😄 Would create the PR for rust-fosdem/rust-fosdem.github.io

**Comment by lucab** [comment]
@mre sure, if you already know you'll be at FOSDEM and want to help, just send a PR for yourself. I think we'd be good around 6 or 7 people. There is still space and helpful hands are always welcome.

**Comment by mre** [comment]
@lucab cool. We already booked the hotel. Looking forward to that. 😃

**Comment by ehiggs** [comment]
[The CfP is open!](http://rust-fosdem.github.io/)

**Comment by badboy** [comment]
@ehiggs Checking in. How's the current status with the CfP? Do we need to spread the word more?

**Comment by ehiggs** [comment]
@badboy we have enough talks already to fill the day. But I'm hopeful that we can have more.

**Comment by ehiggs** [comment]
The schedule is available here:

https://fosdem.org/2018/schedule/track/rust/

**Comment by ehiggs** [comment]
Hi, the devroom is this coming Sunday.

@badboy, @Grummfy, @nical , @mre: will you still be attending? If so, let us know the times you're available and if you have any role preferences and we'll add you to [the rota](https://www.google.com/url?q=https://docs.google.com/spreadsheets/d/1H-IPxBAZrnrG76iuVCcH7dCac8wws9ktCxbl74eJBgQ/edit?usp%3Dsharing&sa=D&ust=1517085123450000&usg=AFQjCNFrZJWDtu0hc4VPIQDFEOrajM1Igg).

**Comment by mre** [comment]
Sing me up, I'll be there. I will also give a talk (at 9:30am in the morning, so I don't expect it to be super crowded at that time, but you'll never know... 😉). Anyway, I would be happy to help. Don't have a role preference. I'm sure you'll find something to do for me.

**Comment by Grummfy** [comment]
if you need help, I can give some help. Otherwise I prefer to have no special place. If there is no place, that's bad, but that's the game ;) Fosdem is what it is

**Comment by badboy** [comment]
Yup, I'll be there. I can do pretty much any role, I'll check times tomorrow.

**Comment by nical** [comment]
Still attending FOSDEM. I'd love to have a room role during the gfx-rs, miri and rustfix talks if that aligns with the organizational needs, I'm of course happy to help during the other talks as well.

**Comment by badboy** [comment]
I guess scheduling is settled than. Times work for me just fine :D

**Comment by ehiggs** [comment]
Hi,
The event has finished. I think it was a success - every seat was taken until the last talk where people start going home (but the last talk was very good so they missed out). Videos are [here](https://tinyurl.com/rust-fosdem18). Thanks to @lucab, @itkovian, @badboy, @mre, @nical for their help.
