### ISSUE TITLE
2017-08-23 Community Team Meeting

### ISSUE THREAD

**Issue by edunham** [rust-community/team#188]
* RustConf Recap

* FOSDEM devroom https://github.com/rust-community/team/issues/187

* Why Rust website https://github.com/rust-community/team/issues/186

* Ad campaigns https://github.com/rust-community/team/issues/184

* Other business?

**Comment by edunham** [comment]
Oops, we switched to Google Docs, so this doesn't need to be here.

**Comment by lucab** [comment]
@edunham is the gdoc publicly accessible? Any pointers to it? Perhaps if that is the new agenda-tracking method, it is worth linking it from the README.
