### ISSUE TITLE
Publishing of RustConf videos

### ISSUE THREAD

**Issue by skade** [rust-community/team#190]
(cc @aturon @wifelette @carols10cents )

I'd like to re-raise the location where RustConf videos are published before they are. Sorry for being a bit late.

The Rust project has an official (also successful and steadily growing) YouTube channel with a management and mod team. It currently has 3k subscribers, steady growth and now over 700k views. I know that it's rarely in the projects spotlight, because it's so nicely chugging along and rarely needs tending. It's odd that our projects conference doesn't publish their videos there. It's also missed audience.

To the request to publish RustConf videos there, I got the following response last year:
https://github.com/rust-community/team/issues/84#issuecomment-250878938

I know and love confreaks (and used to be a customer), but given the current state I'd prefer confreaks to republish videos posted by republishing a playlist from RustVideos, instead of the other way around. The reason simply being: even if we republish the RustConf playlist from Confreaks to our channel, the "subscribe" button is still pointing to Confreaks channel. This is a missed opportunity for people to subscribe to Rust content only, as our channel is also the place where local meetups and other conferences can publish their things.

RustFest is the largest driver of the channel currently (with a sum of views in the ball-park of RustConf). But there's notable consumption of *smaller* videos, like from local meetups and Mozilla stuff, which highlights that the channel acts as a spotlight to smaller projects, a property that ConFreaks doesn't have.

(On a side-note, @carols10cents, I'd also be happy if Rust Belt Rust would take part, but being a community conference, all the points about RustConf being the projects conference don't apply)

**Comment by aturon** [comment]
I'm more than happy to work on getting the content delivered on our YouTube channel. I'll reach out to Leah ASAP.

**Comment by wifelette** [comment]
Heya :)

The videos are nearly ready! The current plan is/was to upload them to _both_ the Confreaks and RustConf YouTube channels. That way we can take advantage of the exposure on both fronts. Confreaks will need the _Manager Permission_ on the RustConf YouTube channel to upload them for us though; I have their email address for it but don't want to post publicly. Can whoever the right person to do that is email me so I can give you the account info for assigning the permissions?

**Comment by badboy** [comment]
@wifelette I will mail you

**Comment by skade** [comment]
I'm closing this, assuming there are no more questions :). Please reopen if there are.

**Comment by badboy** [comment]
Just so the team knows: Confreak now got YouTube access and this will stay for a bit, so they can upload RustConf videos and can make modifications as necessary.
