### ISSUE TITLE
Ship underhanded 2017 prizes

### ISSUE THREAD

**Issue by erickt** [rust-community/team#193]
Update this ticket when you've got the prizes shipped!

**Comment by erickt** [comment]
@bstrie did you get your stuff mailed?

**Comment by aidanhs** [comment]
![underhanded prizes](https://pbs.twimg.com/media/DOqi9dpWAAA4SNO.jpg)
https://twitter.com/aidanhs/status/930735495235231744

:tada: 

Thanks all!
