### ISSUE TITLE
agenda: 13 december 2017

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-community/team#197]
0. **new meeting structure** (5min)
   - Ashley explains general meeting structure and strategy
   - how and when to provide feedback
   - short q&a
1. **subgroups + goals planning** (10min)
   - Ashley intros the spreadsheet (thanks sebastian and manish!) https://docs.google.com/spreadsheets/d/1BnyVgXll6aTVo-yU7Nfy-Vi_Wm7kcogd90sainrhHKc/edit?usp=sharing
   - short q&a re how to use the sheet
2. **educational initiative in india** (10min)
   - Skade intros the project
   - short q&a
   - register interest
3. **additional topics** (if time)

**Comment by skade** [comment]
Closing this as the meeting is over.

**Comment by ashleygwilliams** [comment]
this meeting is actually not over until i run the second one. reopening.

**Comment by skade** [comment]
Oh, damn, sorry about that :(.
