### ISSUE TITLE
Contact !!con organizers about Rust Belt Rust

### ISSUE THREAD

**Issue by erickt** [rust-community/team#20]
bangbangcon.com

**Comment by carols10cents** [comment]
And women who code, and people I'd personally like to see submit :)

**Comment by Manishearth** [comment]
@skade Do you know any groups in Europe who would be interested in the CFP? Especially diversity-oriented groups.

**Comment by erickt** [comment]
@carols10cents: any luck?

**Comment by carols10cents** [comment]
a bit! still working :)

**Comment by carols10cents** [comment]
CFP is closed, so i'm closing this issue!
