### ISSUE TITLE
agenda: 10 jan 2018

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-community/team#206]
- housekeeping (5min)
  - follow up on last week's action items:
    - @Manishearth will draft up a proposal for inviting guests and observers #200 (https://github.com/rust-community/team/pull/207)
    - @jonathandturner will draft up a list of previous rust conf speakers #201 
    - @badboy will draft up a post about 2018 community confs #196 
    - @ashleygwilliams will circle up with core about survey responsibilties #160 
  - goals and subteam planning schedule + plan
- #rust2018 (5min)
   - the collection issue #204 
   - the metablogpost issue #205 cc @booyaa 
- international coordination (5min)
   - let's have a tracking issue for each, with a point person for each?
   - @ashleygwilliams: rustbridge india
   - @badboy @skade @sebasmagri south american rust conf
   - teacher training in india (need people for this)

**Comment by ashleygwilliams** [comment]
action items:
- team to review #207, propose merge next meeting
- speakers list is in private team googledoc, need to fill in and approve emails
   - circle up with @carols10cents and @skade for conf orgs help
- @badboy will have draft PR by this weekend, be ready to review!
- @ashleygwilliams, more about survey after core meeting
- @ashleygwilliams will start google doc for colelcting snippets by category from 2018 blogposts
- rustbridge india
    - @ashleygwilliams to have meeting 11et on friday
    - will start tracking issue
    - circle up with @Manishearth and @skade re coordinating with india teacher training initiative
- south american rust conf
    - meeting 6pm UTC tomorrow
    - @badboy to create tracking issue
- teacher training
    - @skade working on getting a meeting going
    - circle up with @Manishearth about india community

**Comment by badboy** [comment]
LATAM Conf Cooordination: https://github.com/rust-community/team/issues/208
