### ISSUE TITLE
Rust LATAM Conf Coordination

### ISSUE THREAD

**Issue by badboy** [rust-community/team#208]
Idea: A Rust Conference in Latin America
First Call: 11.01.2018, 18:00 UTC
Currently involved: @sebasmagri @badboy @skade @spastorino @anapaulavm

**Comment by badboy** [comment]
We had the call yesterday, led by @spastorino.
Discussion notes:
* Viability of a South American/Latin American Conference
    * Size, aiming for 80-100 people (with 200 as upper cap, depending on venue)
    * Ticket prices largely depending on venue costs
    * Aim of the conference: what audience, what speakers (local/remote)
    * Legal setup
* Moving conference (similar to RustFest)
    * Start in Uruguay (that's where @spastorino is after all)
    * Help from Mexican community (@sebasmagri)
* Current possible time frame: March 2019

Next steps:
* There's a Telegram chat group (ping one of us if interested)
* @sebasmagri sets up preliminary mail accounts (for coordinated communication)
* Thinking about names (once done we check with Core)
* Build strike-group for further planning

**Comment by apiraino** [comment]
@badboy this issue can be closed, I think. The organization for Rust LATAM is established.
