### ISSUE TITLE
agenda: 17 january 2018

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-community/team#209]
- housekeeping (15min)
   - updates on rust bridge @ashleygwilliams
          - u of waterloo https://github.com/rustbridge/team/issues/1
          - online teacher training https://github.com/rustbridge/team/issues/3
   - updates on Rust LATAM Conf https://github.com/rust-community/team/issues/208#issuecomment-357255928 @badboy    
   - updates on convo with Hyderbad folks interested in running a Rust Conf @ranjithrajv
   - merge observer/guest policy @Manishearth https://github.com/rust-community/team/pull/207 (aye/nay)
   - publish 2018 conf blog post https://github.com/rust-lang/blog.rust-lang.org/pull/226 @badboy (aye/nay)
- blog experiment (5min)
   - go over summary document @booyaa 
   - what's left to do
   - schedule moving forward
   - schedule retrospective
- subteams and goals planning (10min)
    - go over RFC @ashleygwilliams
    - what's left to do
    - schedule moving forward
    - schedule retrospective

**Comment by skade** [comment]
I took the liberty of removing the updates for the india training. There are no updates, as me an Mehul are both travelling this week and are having a call after that. I'd like to free the time for other things.

**Comment by ranjithrajv** [comment]
RustBridge India is a proposal by me, I'm not sure why unavailability of Mehul and @skade would give liberty to remove it.

**Comment by ashleygwilliams** [comment]
@ranjithrajv don't worry, you are definitely still on the schedule. as i mentioned in our call yesterday we are also talking about doing a teacher training with some folks from Bangalore- that is what @skade was referring to. sorry to all for the confusion!

**Comment by skade** [comment]
@ranjithrajv this is not about RustBridge. That's another initiative, called "Train the trainers India". RustBridge India is still on. Sorry for the confusion.

**Comment by ranjithrajv** [comment]
Okay! Thanks for the clarity.

**Comment by ashleygwilliams** [comment]
update on the speaker's list:

i have contacted @carols10cents (rustbeltrust) @Manishearth (rustconf) and @badboy (rustfest) re the list that @jonathandturner wrote up. there are a few tasks left on this item:

- fill out all email addresses
- decide policy on use of list
- decide policy on how people on list can manage being on the list
- have confs contact speakers to approve being on the list

this continues to be on target, if anyone wants to help follow up on issue #201

**Comment by ranjithrajv** [comment]
how to join the call?

**Comment by badboy** [comment]
@ranjithrajv Oh, it's just a irc chat in #rust-community on irc.mozilla.org

**Comment by ranjithrajv** [comment]
It shows this.
* #rust-community :You need to be identified to a registered account to join this channel

Add me, nickname #ranjithraj
