### ISSUE TITLE
agenda: 24 january 2018

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-community/team#211]
TWO Meetings, at 4-4:30pm UTC and 10-10:30pm UTC on #rust-community on irc.mozilla.org. EIAL (Easy IRC Access Link): https://kiwiirc.com/client/irc.mozilla.org:+6667/#rust-community

- housekeeping (15min)
   - goals and subteams RFC to be circulated this week and posted on Monday
      - ashley to go through team goal proposals by subteams to fill out comm team goals
   - teams
      - make repos! 
      - write a "charter"
      - determine a meeting cadence
   - comm team meeting - every 2 weeks now?
   - update on #rust2018 progress and call for help
   - Blog posts from last year jay/nay? https://github.com/rust-community/blog.community.rs/pulls
- events team @skade (10min)
    - rust conference in florence italy https://github.com/rust-community/team/issues/210
    - LATAM conf update
    - Events team goal draft
- content team @booyaa 
    - any items?
- switchboard team @Manishearth 
    - any items?
- internationalization team @sebasmagri 
    - any items?
- rustbridge team @ashleygwilliams
    - no updates at the moment
- survey team @jonathandturner 
   - no updates at the moment
- baby duty @erickt (👶 🕐 )
   - change diapers
   - wash bottles
   - cuddle with kiddo

**Comment by jonathandturner** [comment]
No updates on my side.

**Comment by skade** [comment]
Added "Events team goal draft" and "Blog posts from last year"

**Comment by aturon** [comment]
I've [read and summarized](https://paper.dropbox.com/doc/aturons-Rust2018-summaries-Xq57JQv6EkDr0nF5kLsWe) all of the #Rust2018 posts. Are we still thinking of publishing a summary blog post? I'm also planning to draw heavily on quotes etc in the Roadmap RFC itself.

Feel free to ping me when y'all talk about this; I'm happy to help!

**Comment by booyaa** [comment]
@aturon - i was planning a team favourites rather a summary. i'm going to submit my pr to the community blog shortly. hopefully the two don't clash?

**Comment by booyaa** [comment]
Added "Content team goal draft" and community blog post for #Rust2018 team favourites
