### ISSUE TITLE
team info for the README

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-community/team#215]
team leads @skade @booyaa @sebasmagri @jonathandturner @Manishearth please comment with a link to your teams repo (if applicable), call for new members, goals document, meeting schedule

i'll be making a PR to update the README in this repo with all the info :D

Please also add a 2-3 sentence explanation of what your team does.

**Comment by Manishearth** [comment]
Goals: https://docs.google.com/document/d/1ffvu_4dMA9tj119Dbz3GFP_9N65v8-xrwmXPg73QRq8/edit#
Repo: https://github.com/rust-community/switchboard-team
Meeting: Every other Thursday, 9AM PST (alternate Thursday as the community meeting)

**Comment by booyaa** [comment]
Goals: https://docs.google.com/document/d/1fNKaOiV-D2VHdNUPJoGFsM2D10RWNsTGj5WjGHLboqg
Repo: https://github.com/rust-community/content-team
Meeting: every other Tuesday, 5:30-6pm UTC (alternating weeks to community meeting)

**Comment by skade** [comment]
Goals: https://docs.google.com/document/d/1jH2Cz493ILQ79mTR1O8Msgf4v7UmaYp5Mc0UjTNmQ68/edit#
Repo: https://github.com/rust-community/events-team/
Meeting: Every other Wednesday, 5:00-5:30pm (alternate Wednesday as the community meeting)

```
The events team helps events to get better in touch with the rest of the community. We advise and bring you in contact with other organisers. The events team are also the ones to approach if you want to get you meetup featured on the events calendar and subsequently the newsletter.

We are hoping to find new members around the globe, especially outside of Europe and the US.
```

Meeting channel: [Telegram](https://t.me/joinchat/EkKINhHCgZ9llzvPidOssA)
