### ISSUE TITLE
Collect stats to recognize people for the 1 year rust 1.0 anniversary

### ISSUE THREAD

**Issue by carols10cents** [rust-community/team#22]
Ideas from IRC:

- best PR of the year
- most PRs reviewed in the past year
- most lines of tests added
- most lines of docs added
- random draw of someone who made their first commit to rust in the past year
- random draw of someone who made their first bug report to rust in the past year
- random draw of someone who signed up for the forums and made their first post this year
- most code deleted
- rfc with the most comments

Any other ideas? I'm taking the lead on gathering stats for these.

**Comment by brson** [comment]
* Most issues tagged (triaged)
* Most issues closed
* Most troubled PR (PR with most @bors retries)
* Most RFCs accepted
* Most HN upvotes for blog posts
* Most blog posts

We can also award things and events:

* Most epic bikeshed
* Largest apocalypse
* Fastest RFC approval
* Slowest RFC approval
* Most changed RFC (that is, the one where the RFC text had the biggest diff from original submission). Probably can't get the data.

Can also recognize new team members.

Hopefully not all the best numbers go to Moco employees. Could be good to have some that are not just based on numbers simply to have things that aren't dominated by well-known / Moco contributors.

We might pick some tailored to specific individuals we would expect to win, like areas where we know community members made outstanding contributions:

* Most documentation examples added
* Most typos corrected
* Most lints added
* Most dedication to performance improvements

**Comment by carols10cents** [comment]
- Non-Rust-team-members who have commits in Rust, Servo, Cargo, annnnddd.... a nursery crate? Their own crate? I'm trying to make something like [EGOT](https://en.wikipedia.org/wiki/List_of_people_who_have_won_Academy,_Emmy,_Grammy,_and_Tony_Awards) ;)

I'm going to be working on the collection methods of all these stats tomorrow :)

**Comment by skade** [comment]
* Ran an event (those numbers are incredibly hard to collect, but hey)

**Comment by carols10cents** [comment]
> rfc with the most comments

- https://github.com/rust-lang/rfcs/pulls?q=is%3Apr+created%3A%3E2015-05-15+sort%3Acomments-desc

> random draw of someone who made their first commit to rust in the past year

- https://gist.github.com/carols10cents/f89deef257778ed991f299171c7cf1bb#file-new-committers-since-1-0-0-sh

**Comment by carols10cents** [comment]
Some of these are proving to be non-trivial ;) Not impossible though. These, at least, are going to need some human curation if we decide to do them:

* best PR of the year
* Most epic bikeshed
* Largest apocalypse
* Most dedication to performance improvements

**Comment by erickt** [comment]
cc @huonw, who also is apparently collecting numbers.

**Comment by huonw** [comment]
Using https://gist.github.com/huonw/4b2961905627376cef7571e8f8a8c890, I downloaded all of the rust/RFC issue/pull request information to disk, so that analyses can be done without having to wait for the API (github rate limits to 5000/requests per hour, which means that getting each 33K issues + 182K comments individually is somewhat slow)

- https://www.dropbox.com/s/tyysbx0kj66rvd6/rust.tar.gz?dl=0
- https://www.dropbox.com/s/y56ztj9rkugjq03/rfcs.tar.gz?dl=0

I didn't do the other repos, but they're generally much smaller.

**Comment by huonw** [comment]
The random facts I've collected so far are in https://docs.google.com/spreadsheets/d/1iXEarrPtByCueDdatU0HVmXGUqcsWG4vamDqLUtUtRI/edit?usp=sharing . There's some person stuff at the end.

(I used https://gist.github.com/huonw/bcf15e7b75e73af52443c58545ae3178 to summarise the downloaded json files.)

**Comment by huonw** [comment]
(I've updated the previous comment a few times of the past hour, in case someone saw an early version.)

**Comment by skade** [comment]
Here's a community stat:

Rust Berlin: 30 events since October 2014, (20 on the meetup group Rust-Berlin, 8 under the OpenTechSchool banner, one 4-day workshop tent at CCCamp and one 4-day hackgroup at 32C3).
Rust Bay Area: 29 events in total since October 2013 (as per meetup.com history)

**Comment by johannhof** [comment]
Past Meetups from meetup.com (semi-automatic)

| City            | # Meetups |
| --------------- | --- |
| Bay Area | 29 |
| Berlin (incl. OTS) | 28 |
| Paris | 23 |
| Columbus  | 19 |
| San Diego | 14 |
| Hamburg | 12 |
| Sydney | 11 |
| Los Angeles | 10 |
| Portland | 9 |
| Boulder | 8 |
| Seattle | 8 |
| Cologne/Bonn | 6 |
| Darmstadt | 6 |
| Dublin | 6 |
| Skåne | 6 |
| Minneapolis | 6 |
| New York City (both groups) | 6 |
| Amsterdam | 5 |
| Boston | 5 |
| Detroit | 5 |
| London | 5 |
| São Paulo | 5 |
| Phoenix | 4 |
| Romandie | 4 |
| Tokyo | 4 |
| Barcelona | 3 |
| Munich | 3 |
| Wellington | 3 |
| Milano | 3 |
| Montréal | 3 |
| Austin | 2 |
| Chicago | 2 |
| Oakland | 2 |
| Taipei | 2 |
| Toronto | 2 |
| Vancouver | 2 |
| Brisbane | 1 |
| Cebu | 1 |
| Klagenfurt | 1 |
| Madrid | 1 |
| Melbourne | 1  |
| Moscow | 1 |
| Warsaw | 1 |
| Zurich | 1 |
| --------- | ---- |
| __Total__ | __279__ |

**Comment by Manishearth** [comment]
Last year in India we had three launch parties (not all on the launch date) in Pune, Hyderabad, and Bangalore. There have been informal meetups but not large ones due to a lack of community members. There have been a bunch of talks, however, mostly in Mumbai and Hyderabad.

**Comment by skade** [comment]
@johannhof: was written before, CCCamp was forgotten to be announced on meetup. The 32C3 table was a joint thing with Rust Dresden and Cologne though, which I don't know how to count.

**Comment by huonw** [comment]
Is it easy to filter that down to how many events happened since 1.0, rather than ever?

**Comment by skade** [comment]
@huonw due to timezone issues: does the May 15th event count, even if it was before the actual release?

If not, Berlin: (11 Rust-Berlin + 8 OTS + 1 Off-Site-Events) = 20

**Comment by huonw** [comment]
Oh, I'd say it counts: I've just been doing things from midnight on May 15, not worrying about the exact hour.

**Comment by johannhof** [comment]
@huonw mmh that was just a simple JS running through all the meetup group pages, you might want to look at the meetup API, I don't have time for that right now :confused:

**Comment by carols10cents** [comment]
Blergh I dropped the ball on this. Closing, sorry :(
