### ISSUE TITLE
Underhanded Rust Contest

### ISSUE THREAD

**Issue by carols10cents** [rust-community/team#23]
We had an idea in IRC to have a contest where anyone can post something to the users forum, then anyone can vote by "liking" the post and we send swag or something to the person with the most votes.

What should the contest be though?
- Favorite thing about rust
- Thing you learned from rust
- Worst error message
- Fold @erickt's underhanded rust contest into this?

Other ideas?

**Comment by aturon** [comment]
* Interesting thing you've done with Rust

**Comment by erickt** [comment]
Ooh this would be a wonderful opportunity to announce the underhanded rust contest! We just would have to organize it!

**Comment by carols10cents** [comment]
Errrrr so I dropped the ball on getting this together for the anniversary, but we can still do the underhanded rust contest not with the anniversary!

**Comment by erickt** [comment]
@hoverbear said he might help out!

**Comment by Hoverbear** [comment]
I am interested but can't commit a lot right now!

**Comment by skade** [comment]
We got this now at underhanded.rs!
