### ISSUE TITLE
[AGENDA]: 13 June 2018

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-community/team#236]
5-5:30pm UTC on #rust-community on irc.mozilla.org. EIAL (Easy IRC Access Link): https://kiwiirc.com/client/irc.mozilla.org:+6667/#rust-community

- housekeeping (@ashleygwilliams - 15min)
   - capacity building - call for volunteers
       - team updates/blog posts
       - team rfc writing
   - membership update
- survey (@jonathandturner - 5min)
- rustbridge (@oe)
  - rustbridge paris! (5min)
- switchboard (@Manishearth)
- events (@skade)
  - [Last Meeting](https://github.com/rust-community/events-team/issues/32)
  - [FOSS Events Planner](https://github.com/rust-community/foss-events-planner) - need to fill cards (from issues)
  - [List of Rust events](https://docs.google.com/spreadsheets/u/2/d/1Y5cFSdILs03y5FkBkiDWB2x2ae481OYoFzo24KzjJeM/edit) (private as it contains contact info)
  - Defining "Conference Support Policy" (ongoing discussion)
  - Conf experiences
- content (@booyaa - 5min)
  - Need a tech review for content-o-tron request - rust-community/content-o-tron#61
  - Transferring ownership of repos to the rust-community org
    - Blogging template - @booyaa 5mins - rust-community/content-o-tron#42
    - Curation tool - rust-community/content-o-tron#12
- l10n (@sebasmagri)
   - Slowly booting up
   - Some contacts for book translations in .cn and latinamerica
   - Probably gonna be helping the website team with some L10n advice
   - Chinese community liasoning/incubation (Manish)

**Comment by booyaa** [comment]
next meeting #237
