### ISSUE TITLE
2016-05-04 Team Agenda

### ISSUE THREAD

**Issue by erickt** [rust-community/team#24]
Please add agenda items! Here's the initial set I've gotten:

* Rust Community, Core Team, and Conferences (@skade)
* Rust Branding policy
* Survey
 * Replacing demographic question with "Do you self-identify as an underrepresented demographic in technology?" question (@jonathandturner et al)

**Comment by carols10cents** [comment]
birthday!

**Comment by aturon** [comment]
* Diversity/inclusion efforts
  * For RustConf
  * Community-wide

**Comment by aturon** [comment]
* RustConf (http://rustconf.com/)
  * Advice for attracting speakers and attendees from underrepresented groups

**Comment by skade** [comment]
Okay, here's a little more expansion on my topics:

* Core making decisions of community scope without putting them up for discussion
* The obvious (but denied!) US-centrism of core and thus the core community
* The resulting two-class structure
* What's "official" isn't officially communicated
* Events like the announcement of RustConf are not communicated to the community team to make sure they can help in outreach
* Many decisions seems to be made within the same time-zone, with no effort to work against.
* Bad and missing communication to and from other continents
* No willingness to pass on tasks in trust

**Comment by erickt** [comment]
Closing survey on Sunday 5/8, and launching on Monday, 5/9!

**Comment by skade** [comment]
Closing, this meeting is over.
