### ISSUE TITLE
[AGENDA]: 11 July 2018

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-community/team#241]
5-5:30pm UTC on the `community-team\general` in Discord (https://discordapp.com/channels/442252698964721669/443773747350994945) please ask @ashleygwilliams for invites if you don't haven't joined Discord before.

**facilitator** - @ashleygwilliams
**notetaker** - @skade 

- housekeeping (@ashleygwilliams - 2min)
      - upcoming facilitator/notetaker signup
- communication channel discussion (@ashleygwilliams - 5min)
- community calendar incident and mgmt moving forward (@ashleygwilliams, @erickt - 10min)
- website working group (@ashleygwilliams, @skade  - 3min)
- survey (@ashleygwilliams - 5min)
      - leadership/team updates
- rustbridge (@oe - 0min)
  - not much, got some much needed vacation
- events (@skade - 5min)
      - Short work session on [postcards](https://hackmd.io/SCEYRSpKRIK9852CTonyLg#)
      - Conference Booth Planning
- content (@booyaa - 1min)
     - Content-o-Tron intro blog post     
     - updates on Summer Of Code for content-o-tron (@adityac8 - 1min)
- l10n (@sebasmagri - 1min)
      - No major updates. Working on the priorities set in the last meeting (L10n Community Survey)

**Comment by skade** [comment]
# Community team meeting notes, Jul 11

Updates:

Survey team:
* Jonathan is leaving Mozilla
  * Future of the Survey team?
    * Searching for a new lead
    * Hold survey deadline
    * erickt can help out

Events team:
* Presentaction of [meetup postcard](https://hackmd.io/SCEYRSpKRIK9852CTonyLg)
* events team wants to create material for booths in August (rollups, postcards)

Content team:
* booya is writing an introduction to content-o-tron

## Housekeeping

Meeting facilitation:
* There's meeting facilitator and notetaker
* Both roles are open to everyone from the community team and we provide mentorship
* The participation sheet holds that information

Meeting place:
* Decision in 2 weeks: IRC or Discord?
  - What to do with the other channel?
  - Manish would prefer a lightweight client
  - Florian is happy either way
  - Booya is cool with discord
  - General bias towards Discourse
* Subteam leads should pick _one place_ to meet.

Website 2018:
* Community presence on the website
* ag_dubs is team lead (for the whole website)
* Florian is also involved
* For having content added to the page, please ping @ag_dubs or @skade

Community Calendar issue:
* We got notified that events were removed from the community calendar
  - erickt was able to recover them
  - erickt saved the day again
* The calendar has a huge number of people added on trust, all with full editing rights
* Current consideration: adding the events through a form and using a bot account to add them.
* Erick will run regular backups of the calendar
* In the meantime: volunteers wanted to watch the account
* Email to all maintainers of the calendar
* There will be a WG to overhaul the calendar
* Eventually, all permissions for non-team members will be removed
* Manish will diff all the people with permissions on the calendar and the meetup form
* The meetup form will become the default way
