### ISSUE TITLE
[Agenda] 25 July 2018

### ISSUE THREAD

**Issue by skade** [rust-community/team#243]
5-5:30pm UTC on the `community-team\general` in Discord (https://discordapp.com/channels/442252698964721669/443773747350994945) please ask @ashleygwilliams for invites if you don't haven't joined Discord before.

**facilitator** - @skade
**notetaker** - @booyaa

- housekeeping (@ashleygwilliams -Xmin)
- website working group status (@ashleygwilliams, @skade  - 3min)
  - 1st Deadline July
  - Workshop on Sunday
- survey (?? - Xmin)
- rustbridge (@oe - 0min)
  - people have been travelling and i've been very busy with other stuff, so we had to cancel last week's meeting :(
- events (@skade - 2min)
  - Swag meeting on Saturday
  - Getting in touch with conferences over August
- content (@booyaa) - no updates, couldn't run meeting last week because it clashed with Rust meetup I was hosting.
- l10n (@sebasmagri - 1min)
  - Some work on the data gathering survey and some advertising in the RustReach call.

**Comment by Manishearth** [comment]
If we do have time I would like to talk about gsoc for a bit. QUite preliminary

**Comment by booyaa** [comment]
# Community team meeting notes

- Warmup music
 - https://www.youtube.com/watch?v=9jK-NcRmVcw
 - https://www.youtube.com/watch?v=DaHdDVHoUWc

- Housekeeping 
  - @ashleygwilliams - Exercism team has requested community team help for building out their mentor ship program. There will be a call between Ashley and Katrina (Exercism) to go through the specifics. Contact Ashley if you'd like to get involved.
- Website
  - @skade - We need our presence on the website and the we plan to have a rough draft by the end of the month. Subteams (leads) should let @skade and @ashleygwilliams know what they'd like to see on the website, please send before this Sunday so it can be included in a workshop that is being held in Berlin. Ideas can be drawings, snippets of text, projects to link to, icons to glue in. It's fine if it's rough. @ashleygwilliams added if your team has frequently updated content i.e. events, posts, etc please try send in sorted form as this is a good way to embed or subscribe to the content.
- Survey
  - @jonathandturner - the 2018 survey has been drafted and is currently being reviewed. @Manishearth  @sebasmagri  are coordinating the translation of the survey and this will be launched in tandem. The plan is to go live in the next couple of weeks.
- Rustbridge
  - @oe no updates
- Events
  - @skade there's going to be a swag workshop on Saturday organised by @killercupcake (Pascal) and @skade. The goal is to get a package ready to send to the printers forthe conferences by next month.
- Content
  - @booyaa no updates
- i18n
  - @sebasmagri had an awesome call with the RustReach group to talk about i18n/i10n, they've been trying to figure out what data to gather to integrate with the survey.
- AOB
  - @Manishearth and @ashleygwilliams to discuss GSoC before discuss with the team at large.
  - @skade mentioned in context of the website, that we should find ways to integrate dynamic content in a way that's easy to maintain and does rot immediate. Example give was how many channels are still active in this page https://www.rust-lang.org/en-US/community.html

**Comment by skade** [comment]
@booyaa Thanks for the notes. I made a small edition, making it clear that the channel list is a _negative_ example.
