### ISSUE TITLE
Include a link to State of Rust 2017 in the FAQ

### ISSUE THREAD

**Issue by pierre-l** [rust-community/team#246]
I've seen the link to [the results of State of Rust 2016](https://blog.rust-lang.org/2016/06/30/State-of-Rust-Survey-2016.html) at the bottom of the [FAQ](https://github.com/rust-community/team/wiki/State-of-the-Rust-Language-Community-Survey-FAQ), it would be cool to include [the results of State of Rust 2017](https://blog.rust-lang.org/2017/09/05/Rust-2017-Survey-Results.html) too.

**Comment by oe** [comment]
Done!

**Comment by pierre-l** [comment]
Thank you!
