### ISSUE TITLE
[Agenda] 22 Aug 2018

### ISSUE THREAD

**Issue by skade** [rust-community/team#248]
5-5:30pm UTC on the `community-team\general` in Discord (https://discordapp.com/channels/442252698964721669/443773747350994945) please ask @ashleygwilliams for invites if you don't haven't joined Discord before.

**facilitator** - @skade
**notetaker** - @badboy

- housekeeping (@ashleygwilliams?, @skade  -Xmin)
- website working group status (@skade  - 3min)
- survey (@jonathandturner  - Xmin)
- rustbridge (@oe - 5min)
  - exercism updates
  - rustconf rustbridge summary?? maybe?
- events (@skade - 2min)
   - no news
- content (@booyaa) 
- l10n (@sebasmagri - 1min)

**Comment by badboy** [comment]
* August was tough, adhoc meetings happened
* RustConf done, FrOSCon upcoming this weekend
    * Team with a booth (Stickers, cards, embedded showcase)
* Website
    * Found good layout to present every subgroup
    * Need content answering questions:
        * What do we want on the website?
        * Do we have an image for it?
        * What does our group do?
        * How is it important to Rust?
    * @skade wants your notes/ideas in whatever (readable) form
* Survey: Status?
    * @manishearth: ~5000 responses
    * A bit more promotion needed!
    * Deadline 8th September
* Rustbridge
    * @oe: Exercism meeting
        * Improvements to Rust course
        * Rustlings well received by learners
        * Moving Rustling exercises into Exercism course (as alternative)
        * Needs manual work
    * Replace rustbridge website with subsection on new site
        * Some copy is written
* Events
    * No news
* Content
    * No updates
* i10n
    * No news
    * @sebasmagri : translation for new website?
        * Content once it's there
        * Otherwise: needs coordination with @ag_dubs
* Misc
    * Sticker files & postcards in [resources repository](https://github.com/rust-community/resources)
    * @skade  on vacation in October
    * RustFest is happening, stay tuned!
    * Rust Belt Rust announcements coming, too

**Comment by booyaa** [comment]
replaced by #249
