### ISSUE TITLE
Conference coordination

### ISSUE THREAD

**Issue by aturon** [rust-community/team#25]
The community team is a good place for people to coordinate Rust conferences (whether they are on the team or not). We need to advertise this more widely, to avoid accidental overlap.

@erickt [started a thread](https://users.rust-lang.org/t/2016-2017-rust-conference-coordination/5694), but I wonder if we need at least a high-profile, permanent link?

In addition, it would be great to have a static page somewhere listing all of the conferences we're aware of. We already list the [user groups](https://www.rust-lang.org/user-groups.html) from the [community page](https://www.rust-lang.org/community.html), so having a conference page also linked seems pretty straightforward. Maybe something like https://github.com/golang/go/wiki/Conferences

**Comment by erickt** [comment]
Anyone want to take ownership for implementing this?

**Comment by skade** [comment]
I love http://rubyconferences.org/ and it can probably be ported.

**Comment by skade** [comment]
There was a long thread on the rust-community mailing list about which conferences to try to be present at, too. We should dig that out.

**Comment by skade** [comment]
Also, there was an effort last year to list events to try to be present at. We should revive that.

**Comment by erickt** [comment]
2016 conferences happened! Now it's all about [2017!](https://github.com/rust-community/team/issues/113).
