### ISSUE TITLE
Agenda: 19 September 2018

### ISSUE THREAD

**Issue by booyaa** [rust-community/team#250]
5-5:30pm UTC on the `community-team\general` in Discord (https://discordapp.com/channels/442252698964721669/443773747350994945) please ask @ashleygwilliams for invites if you don't haven't joined Discord before.

- housekeeping (`facilitator` - 12min)
   - TWiR joining the Comm Team - (@ashleygwilliams - 3min)
   - Moving meeting time due to conflict with Berlin Hack and Learn - (@ashleygwilliams - 2min)
   - new swag program - (@ashleygwilliams - 5min)
   - keynote complaint - (@ashleygwilliams -2min)
- survey (@jonathandturner - ??min)
- rustbridge (@oe - 0min)
  - mostly keeping everyone in the loop about past things
- events (@skade - ??min)
   - new events budget process - (@ashleygwilliams - 3min)
- content (@booyaa - 3mins)
   - Refocussing the content-o-tron and the team
   - Welcome TWiR !
- l10n (@sebasmagri - 1min)
  - No updates. Pending meeting with website team

Note received on IRC we probably need to check?:
```
https://lincolnloop.com/blog/saying-goodbye-botbotme/
apparently botbot.me is shutting down, and i know a lot of our channels are logged by botbot
any plans on what to do about this? maybe save the old logs somewhere?
or merge them into logbot somehow?
```

**Comment by skade** [comment]
# Community team Meeting, Sept 19 2018

## Housekeeping 
* This Week in Rust will join the content team
* Discussions about moving the meeting because of collisions
    * generally positive response, we will doodle
* Devswag for distributing swag?
    * liv is not thrilled about stickermule
    * shipping cost might be prohibitive
    * finding other vendors is hard
* complaint email
    * gravitating towards no response

## Updates

* Survey
    * Survey is closed
* Events
    * RustConf people will participate in the events team
    * budget process
        * a process will be put in place to make money allocation more transparent
        * also make more transparent how to request it
        * we also want to make transparent who gets money
* Content
    * moves towards content campaigns, expects more activity
* i18n
    * no updates, syncing with website team

## Other

logbot for IRC shutting down
* Generally not seen as a concern
    * Checking if all old meeting notes were taken over might help
