### ISSUE TITLE
Agenda: 03 Oct 2018

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-community/team#251]
5-5:30pm UTC on the `community-team\general` in Discord (https://discordapp.com/channels/442252698964721669/443773747350994945) please ask @ashleygwilliams for invites if you don't haven't joined Discord before.

- housekeeping (@ashleygwilliams - 10min)
   - as the year winds down, let's think about:
       - doing a year in review (5min)
       - goal setting for next year (5min)
- survey (@jonathandturner - 1min)
  - in-progress: merging all survey results together, automatic translation, and some basic data normalization.
- content (@booyaa - 2mins)
  - changing meeting date/time
  - closing [old issues](https://github.com/rust-community/content-team/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+-label%3Aagenda+-label%3A%22good+first+issue%22+) on team repo.
- l10n (@sebasmagri - 1min)
  - No updates.

**Comment by nasa42** [comment]
The [calendar](https://calendar.google.com/calendar/embed?src=apd9vmbc22egenmtu5l6c5jbfc@group.calendar.google.com) lists Rust Community Team Meeting twice on alternate Wednesdays. It should be fixed.

**Comment by jonathandturner** [comment]
# Housekeeping items

- Thoughts on year in review for the community team
  - There will be a for formal call for content in 2 weeks
  - technetos: Not that we are not keeping track of progress made already but down the line (like 2 years) it would be nice to be able to pull up a single page and see progress from 0 til now as far as things done, by who, for what, lessons learned and so on

- Thoughts on goal setting for next year
  - jturner: Can we pull in the global communities into the community more?
  - Right now Manish sits in on language-specific channels to help out with community tasks, might be nice to generalize this
  - Might be nice to have a community team internal "year in review" as part of the planning

# Subteam updates

## Survey team

- @mgattozzi has put together a master spreadsheet where we're merging and normalizing our data
- next steps are doing the translations
- is there a plan to release the data portion prior to the translations?
  - that's a great question! If there's a request to do so, we can definitely explore
- and/or an estimate on the time required for the translation? (can i help by calling for resources or anything for ya'll?)
  - I don't have an estimate. There's been a lot of travel in the team, but hopefully that'll settle down enough to get an estimate
- We should have the translators we need to translate the answers
- Ask: can we also document the process
  - Manish: Not rn, I've been travelling and busy. I can do it once things settle down!

## Content team

- Currently voting on moving the meeting: 
  - https://doodle.com/poll/w3evtpqniaa63kyy
  - The current winner is Monday 1700 UTC
- Will announce the new meeting datetime at our next meeting and possibly last meeting next Tues
- We're also doing a little bit of house keeping and closing off any open issues that haven't been resolved, if you issue is in this list please chime in and we'll not close it: https://github.com/rust-community/content-team/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+-label%3Aagenda+-label%3A%22good+first+issue%22+
