### ISSUE TITLE
Agenda: 31 October 2018

### ISSUE THREAD

**Issue by booyaa** [rust-community/team#253]
5-5:30pm UTC on the `community-team\general` in Discord (https://discordapp.com/channels/442252698964721669/443773747350994945) please ask @ashleygwilliams for invites if you don't haven't joined Discord before.

Count down to meeting: [link](https://www.timeanddate.com/countdown/launch?iso=20181031T17&p0=1440&msg=Team+Meeting&font=cursive&csz=1)

- housekeeping (@booyaa - 7min)
   - start process of proposing that ashley step down as lead - forming a leadership team (@ashleygwilliams - 5min)
   - ferris official RFC - future design team efforts on the comm team? (@ashleygwilliams - 2min)
- survey (@jonathandturner - ??min)
- rustbridge (@oe - 0min)
- events (@skade - 2min)
  * Integrating RustConf -- tomorrow
  * MozFest report
- content (@booyaa) - no updates
- l10n (@sebasmagri - ??min)

**Comment by booyaa** [comment]
closes #252

**Comment by Manishearth** [comment]
Agenda item proposal: Better integrating https://github.com/rust-unofficial/ into the team.
