### ISSUE TITLE
Discourse: install saved searches plugin

### ISSUE THREAD

**Issue by jethrogb** [rust-community/team#259]
Would it be possible to install the [saved searches plugin](https://meta.discourse.org/t/saved-searches-plugin/67901/) for Discourse? This is useful for crate owners who want to keep track of support questions.

Previous discussion:
https://users.rust-lang.org/t/saved-searches-plugin/21019
https://users.rust-lang.org/t/install-discourse-saved-searches-plugin-notifications-for-crate-maintainers/18066

**Comment by carols10cents** [comment]
I now have admin perms and would be happy to take care of this. @rust-community/community-team any objections to me doing this? (I will wait one week, until March 27, 2019, for any response)

**Comment by skade** [comment]
@carols10cents +1 from me

**Comment by badboy** [comment]
No objections from me.

**Comment by carols10cents** [comment]
Ok, slight problem... we're on a hosted Discourse with the Business plan, [which only supports a few plugins](https://payments.discourse.org/plugins#business). Saved search isn't one of them. So unfortunately I don't think we can do this... if someone finds a way, please reopen and let me know what to do ❤️
