### ISSUE TITLE
Discourse: disable "post-notice" alerts

### ISSUE THREAD

**Issue by jethrogb** [rust-community/team#260]
A recent Discourse update has added "post-notice" alerts throughout the software, with messages such as "Xyz is a new user, please welcome them" and "Abc hasn't posted in a while". The way these are currently formatted, I personally find these *extremely* distracting when reading a topic.

Unfortunately, Discourse does not let users disable this by themselves. There have been a couple of topics on this on the Discourse Meta forum, but they keep getting deleted, so I can't really link to them for you now.

I think there are a couple of options:

1. Change the `min post notice tl` setting under `/admin`. This hides the alerts for all users under the specified TL.
2. Add the following CSS to the theme. This hides the alerts for everyone
```css
.post-notice {
  display: none; 
}
```
3. Create a second theme from the main theme with the CSS above. This allows users to individually choose whether they want to see these alerts or not.
4. Change the CSS in such a way that the alerts are less obtrusive and can always be shown.

**Comment by carols10cents** [comment]
I now have admin perms and would be happy to take care of this. @rust-community/community-team any objections to me doing this? (I will wait one week, until March 27, 2019, for any response)

**Comment by jethrogb** [comment]
Just to be clear, which option do you intend to do?

**Comment by carols10cents** [comment]
Sorry, I edited: I'd probably just hide them.

**Comment by skade** [comment]
@carols10cents +1 from me.

**Comment by badboy** [comment]
No objections from me.

**Comment by carols10cents** [comment]
Great, done!
