### ISSUE TITLE
Agenda: June 26, 2019

### ISSUE THREAD

**Issue by technetos** [rust-community/team#267]
# Community Team Meeting Agenda June 26, 2019

+ Proposed changes to Internationalization/localization WG - @Manishearth 
+ Addition of website team - @skade

**Comment by Manishearth** [comment]
https://github.com/rust-community/team/issues/266

**Comment by technetos** [comment]
# Community Team Meeting June 26, 2019 Notes

@Manishearth
+ Rename the l10n working group to the I18n working group.  
+ Create a new discord and mailing list for the l18n working group.
+ See https://github.com/rust-community/team/issues/266

@skade 
+ Create website team
+ Current plan of action for the website
  + fix bugs
  + deal with missing pages
  + In general stabilize the website so its a good foundation for making changes to it in the future
