### ISSUE TITLE
Fixed meeting time of UTC 4pm discourages participation from East Asia & Oceania

### ISSUE THREAD

**Issue by huonw** [rust-community/team#27]
That meeting time is the middle of the night from ~UTC+6 (Bangladesh) to ~UTC-10 (Hawaii), which includes all of China, Indonesia, Japan, the Korean peninsula, Australia, New Zealand, Pacific islands, etc. 

http://www.timeanddate.com/worldclock/converted.html?iso=20160511T16&p1=0&p2=240&p3=264&p4=103&p5=33&p6=248&p7=108&p8=28&p9=73

One approach in global meetings I've been in in the past is to have the time alternate between weeks.

**Comment by Manishearth** [comment]
Agreed. The time is sort of okay for me -- I'm okay with a meeting at 10:30pm once a week, but it would be nice if it was during the day.


Though from core+community it's just you, me, and @skade who would be able to attend an Asia-centered meeting.

**Comment by skade** [comment]
I'm good with moving meetings and if full attendance is impossible, I'd prefer rolling attendance.

**Comment by erickt** [comment]
Good idea, I'll bring it up during today's meeting.

**Comment by erickt** [comment]
This has been announced! We'll experiment with alternating between [2am UTC](http://everytimezone.com/#2016-6-7,840,cn3) and [4pm UTC](http://everytimezone.com/#2016-6-15,-60,cn3)!
