### ISSUE TITLE
Remove Jonathan Turner from team

### ISSUE THREAD

**Issue by jonathandturner** [rust-community/team#270]
Jonathan stepped down from the team. Next steps are to:

* [x] Remove Jonathan from the email list
* [x] Remove Jonathan from the team list on the Rust website
* [x] Add Jonathan to Alumni
* [x] Remove Community Team role on discord for Jonathan

**Comment by skade** [comment]
@jonathandturner You can do that by putting a pull request to https://github.com/rust-lang/team

**Comment by JohnTitor** [comment]
Removed from the team list and perhaps the email list also. The remaining task is to remove Community Team role on discord for Jonathan. (I'm not sure we should add Jonathan to Alumni.)

**Comment by JohnTitor** [comment]
thanks for the work @jonathandturner!
I'm going to close this issue because all the tasks have been done.
