### ISSUE TITLE
Meeting ageda on README is outdated?

### ISSUE THREAD

**Issue by JohnTitor** [rust-community/team#272]
It seems the meeting agenda on README is outdated. Should we replace it with something?

**Comment by apiraino** [comment]
related question: is this repo still actively used? I see there lot of issues that can be closed and no recent update

**Comment by JohnTitor** [comment]
@apiraino We use this repository for the discussion and putting the agenda. But yes, we should triage inactive issues.

**Comment by apiraino** [comment]
I think most of pre-2019 issues can be safely closed but it's your call. If you need help on that I can squeeze some time for triaging
