### ISSUE TITLE
Community Team Meeting Agenda October 23, 2019

### ISSUE THREAD

**Issue by technetos** [rust-community/team#273]
# Community Team Meeting October 23, 2019

+ Johnathan is leaving the team #270 
  + The survey needs someone to champion it since it was formerly Johnathan.  
+ Update team page on website and this repo
  + Should we find new lead?

**Comment by JohnTitor** [comment]
@technetos btw, what time (and time zone) does the meeting start?

**Comment by JohnTitor** [comment]
Ah, I missed it. README says it's 5PM UTC.

**Comment by technetos** [comment]
# Community Team Meeting Notes October 23, 2019

+ Johnathan left the team
  + https://github.com/rust-community/team/issues/270
  + @XAMPPRocky volunteered to get the current survey out and make a write up with steps for others to follow in the future.  No one has been selected yet to managed the survey in general.  
+ The website has been updated to reflect the lack of a team lead
  + Since we did not have everyone on the community team at the meeting it was decided to put off finding a new team lead until the next meeting and an [issue][1] was created to track that process.  

[1]: https://github.com/rust-community/team/issues/274#issue-511469192
