### ISSUE TITLE
Community Team Meeting Agenda November 27, 2019

### ISSUE THREAD

**Issue by technetos** [rust-community/team#275]
# Community Team Meeting November 27, 2019
+ Discuss the future of the community team. @technetos 
  + If necessary figure out who will be the new team lead.
    + https://github.com/rust-community/team/issues/274
   + we should triage repos and issues under this org @JohnTitor  
   + how about skade's suggestion? @JohnTitor 
+ What's the current status for community.rs? @JohnTitor 
+ Discussion of the learning team @fmoko

**Comment by vertexclique** [comment]
From my side I can add:

Discussion on announcing "rust translators medium". Medium is for all language translators and language leads. This medium will allow us to have a common synchronization platform for all main localization team and all translation subteams.
Which can be consist of two things(for now):
- Weekly meetings at #wg-localization in Zulip
- A mailing list for all localization teams.

Later:
- Notification system for all translations (needs update, newly created, needs review)

As a side note we might need to think about making this a team.

**Comment by technetos** [comment]
# Comm-Team Meeting Notes November 27, 2019

A lot of discussion was had around the future of the community team.  Overall the general consensus was to keep the community team around as an umbrella team.  In the past restructuring of the community team into smaller teams has resulted in more meetings and ultimately smaller teams getting lost / forgotten.  

The creation of a Community Leadership team that would serve as an overarching support team for the community team at large was discussed.   This team would be responsible to set the
general communities current mission and make sure teams stay productive and frictionless.  The details for this team are still tbd.  

A write up from @skade was proposed as a starting point for these discussions and is linked [here][skades proposal]

The creation of a new Learning team / working group championed by @fmoko was discussed.  The Learning team would encompass rustbridge, RBE and rust teaching materials in general, although whether the Learning team would be under the community team umbrella or not is still tbd.  

@vertexclique Has been doing a lot of stuff with the i18n WG and will hopefully be running the WG soon.  

[skades proposal]: https://hackmd.io/t-tPFrwFQWm1KmDlO4njWg?view
