### ISSUE TITLE
Community Team Meeting Agenda June 24, 2020

### ISSUE THREAD

**Issue by technetos** [rust-community/team#283]
# Community Team Meeting June 24, 2020

**Comment by cdmistman** [comment]
There should be some discussion on transitioning `master` branches to `main`, as well as vetting for other potentially offensive terminologies in community repos.

I also propose we consider hosting some kind of community event (hackathon is the easiest and first thing that comes to mind)

**Comment by Manishearth** [comment]
@cdmistman this has already been discussed and mostly decided on by the core team

https://users.rust-lang.org/t/inclusive-naming-of-default-branches/44829/9

GitHub is implementing tooling around this and their [recommendation is to wait for it](https://github.com/github/renaming/), so currently we plan to do so. Once that comes out we'll be coordinating a decision.
