### ISSUE TITLE
 Community Team Meeting Agenda August 26, 2020

### ISSUE THREAD

**Issue by technetos** [rust-community/team#285]
# Community Team Meeting August 26, 2020

**Comment by cdmistman** [comment]
I'd like to discuss moving the TWiR repository into a different GitHub organization, and the steps needed to do this migration.

**Comment by XAMPPRocky** [comment]
Updates to the community page need a review. https://github.com/rust-lang/www.rust-lang.org/pull/1203

**Comment by technetos** [comment]
# Meeting Notes

Not much to discuss in the meeting today, meeting notes follow.  

@cdmistman @nellshamrell - We plan to migrate TWiR into rust-lang.  Make @Manishearth an admin in the current repo so they can transfer it to the rust-lang org.  - edited according to [this comment][1]

@XAMPPRocky - The changes to the website have been approved and will move forward as planned.  

[1]: https://github.com/rust-community/team/issues/285#issuecomment-681013467

**Comment by Manishearth** [comment]
Other way around, one of you needs to make me an admin to facilitate the transfer. Though I forget what perms you need precisely so it's possible Nell will also be able to to it herself if she's an admin
