### ISSUE TITLE
Rust Survey - polish version

### ISSUE THREAD

**Issue by hanusek** [rust-community/team#286]
The Polish version of the survey is incorrect.
Probably the questions are mixed up with the answers.

https://docs.google.com/forms/d/e/1FAIpQLScBvNYpnh4fUyCUaUt6Er7jA96HONN7aoQFSloGGPnZPq8z4w/viewform

**Comment by nikomatsakis** [comment]
cc @xanewok

**Comment by Xanewok** [comment]
Oh, that does look troubling, indeed. Thanks for noticing! I'm on it.

**Comment by JohnTitor** [comment]
Closing as resolved/outdated.
