### ISSUE TITLE
The rust-community github org could use an icon

### ISSUE THREAD

**Issue by carols10cents** [rust-community/team#31]
Right now it's just a github-generated one
Just the rust logo or that + something that says community? Combine a rust logo and a globe somehow???

**Comment by jdm** [comment]
http://www.csdtrzic.org/wp-content/uploads/2013/06/cirlce-of-hands.jpg surrounding the Rust logo.

**Comment by jdm** [comment]
<img width="555" alt="screen shot 2016-05-18 at 10 15 47 pm" src="https://cloud.githubusercontent.com/assets/27658/15381558/1e12d360-1d46-11e6-8f9d-5487b3e3d6c0.png">

**Comment by carols10cents** [comment]
Love the concept! Looking for a CC licensed similar image now... http://www.gettyimages.com/detail/photo/group-of-human-hands-showing-unity-royalty-free-image/147318788

**Comment by carols10cents** [comment]
There's this: https://pixabay.com/en/circle-hands-teamwork-community-312343/

<img src="https://pixabay.com/static/uploads/photo/2014/04/03/11/51/circle-312343_960_720.png" />

**Comment by carols10cents** [comment]
It is done!! <img src="https://avatars1.githubusercontent.com/u/16257301?v=3&s=200" width="40" />
