### ISSUE TITLE
Rust by example

### ISSUE THREAD

**Issue by skade** [rust-community/team#34]
RBE is a little unmaintained, more writers
would be great. See if we can find a way to change that.

Especially a great resource for upcoming workshops.

**Comment by steveklabnik** [comment]
:+1:

**Comment by skade** [comment]
@steveklabnik hows the state of things there, this predates the docs team?

Can we close this over here or should we try to find people for RBE to be working with the docs team?

**Comment by steveklabnik** [comment]
I would assume that this is the docs team's job now, yeah.
