### ISSUE TITLE
2016-06-23 @ 2am UTC Community Team meeting

### ISSUE THREAD

**Issue by erickt** [rust-community/team#39]
[Last Week](https://github.com/rust-community/team/issues/37)

Agenda:

* [nominated](https://github.com/rust-community/team/labels/nominated)
* Survey blog post draft
* [RustBridge Meeting](https://github.com/rust-community/rustbridge/issues/7)
* [2017 RustConf Planning](https://github.com/rust-community/team/issues/40)
* [Rust Forge](https://github.com/rust-community/team/issues/38)
* homu update

**Comment by skade** [comment]
@erickt Is this 2am or 2pm?

**Comment by frewsxcv** [comment]
I won't speak for erickt, but the Rust Community Google Calendar also says [2am UTC](http://everytimezone.com/#2016-6-22,840,cn3)

**Comment by skade** [comment]
@frewsxcv Argh, on the 23rd. I was thinking it was 2am wednesday, and though I missed it :)

**Comment by erickt** [comment]
Sorry about that, I think I messed up the timezone on the calendar invite :( I think it's all fixed now though.

**Comment by jonathandturner** [comment]
For the agenda:
* Survey blog post draft

**Comment by skade** [comment]
Closing, it's in the past :).
