### ISSUE TITLE
2017 RustConf Planning

### ISSUE THREAD

**Issue by erickt** [rust-community/team#40]
While the 2016 RustConf hasn't happened yet, lets start tracking what we could do better in 2017.
- The registration was opened a bit late, and we've heard from some people they've already have other activities planned when it opened.
- Our community might be large enough to have two days of talks.
- We should have some time carved out for community organization and birds-of-a-feather subgroup meetings.

**Comment by Manishearth** [comment]
I really like the mentorship program @skade & co are using in rustfest. The language used there is great too; it explicitly tackles one of the factors affecting diversity -- qualified people not being confident enough to submit a talk proposal (or apply for a job, or ...). Perhaps we could adopt something similar?

**Comment by skade** [comment]
As RustConf wasn't debated, discussed and planned within the community team, neither in outset, construction or goals, I'd prefer to first talk about the involvement of the team first. I don't see our jobs as mere additional hands within the project.

I'm happy to offer mentorship-like infrastructure on a larger scale in the Rust community and I would have if I had been involved in the RustConf planning (the project is ~3 years old, it's a standard implementation now), there's nothing barring the whole thing from being offered more widely.

**Comment by aturon** [comment]
@skade Yes, absolutely agreed that we should nail down the community team's role in putting together the conference, as we discussed previously. I think it's a good item to dedicate a meeting/call to, perhaps after the current round of conferences are complete?

**Comment by skade** [comment]
Do you mind if I rename this to "2017 conf planning" and close #25?

**Comment by aturon** [comment]
Sounds good to me!

**Comment by erickt** [comment]
Closing in favor of #113.
