### ISSUE TITLE
2016-06-29 meeting agenda

### ISSUE THREAD

**Issue by erickt** [rust-community/team#42]
* meeting visibility
* [#rust-community rules](https://github.com/rust-community/team/issues/43)
* [MozFest](https://github.com/rust-community/team/issues/44)
* [nominated](https://github.com/rust-community/team/labels/nominated)

**Comment by bstrie** [comment]
I'd like to add an item about increasing the transparency wrt the weekly goings-on of the Mozilla devs. That's a hole in Rust's development that TWiR hasn't been able to fill. I know there used to be weekly meetings where people could give broad overviews of things that they were working on, which was perfect for helping to understand what things were in the pipeline. As of right now it feels like we only hear about things that are either waaaaaaay far off (via Niko's blog) or finished, polished, and landing (via the official blog). For example, I'd been on tenterhooks regarding the progress of https://internals.rust-lang.org/t/enabling-mir-by-default/3555 , which goes days at a time without comments (and I certainly wasn't aware that Niko had been on vacation). Requesting @aturon's presence for this, ideally.

**Comment by skade** [comment]
Also, I'd like to know if we should give people the possibility to sign up for news at our page. (for journalistic consumption)
