### ISSUE TITLE
MozFest involvement

### ISSUE THREAD

**Issue by skade** [rust-community/team#44]
MozFest 2016 is coming, do we want to be involved this year?

**Comment by jdm** [comment]
I don't see a clear relevance for anything Rust-related right now, given that the focus of MozFest is traditionally digital literacy, openness in tech-aligned fields like science/journalism, privacy/security, and the web. Did you have something particular in mind?

**Comment by skade** [comment]
How are these fields not Rust related, especially community-team related? We do teaching, we currently set up a bridge, we do outreach.

Also, it's a good place to meet and plan things around.

**Comment by Manishearth** [comment]
> We do teaching, we currently set up a bridge, we do outreach.

That is what we _do_, but the field we do it in is still different. We (are trying to) teach programmers Rust.

MozFest is trying to boost efforts that teach _the general public_ about the web/privacy/etc.

**Comment by skade** [comment]
Bridges for example are very fundamentally about reaching the general public and empowering competence.

**Comment by skade** [comment]
To clarify further: Last years Mozfest had multiple tracks about online community building, online harassment, moderation, teaching and outreach methods. These are all things we have experience in.

I wasn't implying that we need to talk about our technology, we have much more beyond that.

**Comment by brson** [comment]
With Mozilla fully-committing to Rust-in-Firefox, there is a fair bit of internal movement towards promoting Rust through the standard Mozilla channels. For example, there are the beginnings of an effort to have the Mozilla participation team hold Rust events (there was a thread on rust-community about this). We may soon find that various divisions in Moz are much more willing to consider Rust-anything than they have been in the past.

If somebody is motivated to propose something for mozfest it might be worth it. Need to consider the 'open internet' theme, but there's surely ways to work Rust into that.

Here's the link to make a proposal, but deadline is *August 1*: https://mozillafestival.org/proposals

**Comment by skade** [comment]
I'll close this, it seems we haven't moved fast enough.
