### ISSUE TITLE
2016-07-27 Community Team Meeting

### ISSUE THREAD

**Issue by brson** [rust-community/team#49]
Meeting at [4pm UTC](http://everytimezone.com/#2016-3-29,1680,cn3) on #rust-community on irc.mozilla.org. [Last week's agenda](https://github.com/rust-community/team/issues/49).

Action Items:
- The team ought to start thinking about what projects they want to help on, or start up.
- @booyaa is going to investigate how we can get meetup communities to be more engaged. Possibly by enhancing rust-community/talks?
- @Manishearth was volunteered by everyone to start the Underhanded Rust Contest 😛
- @Manishearth and @booyaa might have some time to help out with bors
- @booyaa is going to investigate better ways to host #rust-beginners, since many companies block irc. He's checking out slack, mattermost, and zulip.

Agenda:
- friend of the tree (brson)

**Comment by carols10cents** [comment]
* May I take the email addresses of people who answered the survey and said they were interested in traveling to pittsburgh for a conference AND checked yes to "may we email you" and contact them directly about Rust Belt Rust?

**Comment by carols10cents** [comment]
* More generally, @jonathandturner is interested in discussing outreach plans using the survey data, such as contacting companies who expressed interest in the community team contacting them

**Comment by carols10cents** [comment]
Regarding my request, we discussed it and I'm going to send one email about all 3 conferences on Aug 1. Any other thoughts between now and then, please add to this issue! https://github.com/rust-community/team/issues/50

**Comment by edunham** [comment]
@booyaa, have you considered gitter.im channels for rust-beginners alternatives? They're as pretty-looking and browser-friendly as Slack, but tied to GitHub repos and use GitHub login so it's one less set of credentials to juggle. The one-channel-per-repo aspect could be limiting, though.

**Comment by erickt** [comment]
Summary:
* [Friend-of-the-Forest](https://github.com/rust-community/team/issues/51)
* @carols10cents is working out how to contact survey responders about the upcoming [conferences](https://github.com/rust-community/team/issues/50)
* @edunham, @japaric will help out @locks and @booyaa in getting homu-on-heroku working.
