### ISSUE TITLE
Write up a blurb for the community team on users.rust-lang.org

### ISSUE THREAD

**Issue by erickt** [rust-community/team#5]
Our brand new category on https://users.rust-lang.org/t/about-the-community-category/5046 currently has the default description. We need a better one. @brson: I don't appear to have permission to modify this banner, could you give us all rights to it?

What should we put in it? Maybe something [along the lines of](https://www.rust-lang.org/community.html):

---

Rust is an amazing programming language, but its greatest strength is its kind and inclusive community.

We are committed to providing a friendly, safe and welcoming environment for all, regardless of gender, sexual orientation, disability, ethnicity, religion, or similar personal characteristic. Our [code of conduct](https://www.rust-lang.org/conduct.html) sets the standards for behavior in all official Rust forums.

This category is about organizing people to help form meetups, events, and other activities that help educate and expand our community.

---

Feel free to improve. I'm no document engineer :)

**Comment by skade** [comment]
I'll close this now and replace it by #83. We are around, but we should document what we do.
