### ISSUE TITLE
Email respondents to survey interested in conferences on Aug 1

### ISSUE THREAD

**Issue by carols10cents** [rust-community/team#50]
When rustfest tickets go on sale. To anyone who entered an email and expressed interest in attending conferences in Portland, Pittsburgh, or Berlin.

Content will be basically https://blog.rust-lang.org/2016/07/25/conf-lineup.html. 

I will make it clear that:
- I got their emails from the rust survey
- This is a one-time email, not an ongoing mailing list
- I am a community team member

**Comment by erickt** [comment]
Since we have people said they'd be interested in traveling to multiple conferences, we could bucket them into just pointing people at RustBelt and RustConf if they said they wanted to travel to just Portland and Pittsburgh, but not Berlin. Should be pretty simple to calculate.

**Comment by carols10cents** [comment]
Yeah shouldn't be too bad. Max 7 different emails? 

1. Portland
2. Pittsburgh
3. Berlin
4. Portland & Pittsburgh
5. Portland & Berlin
6. Pittsburgh & Berlin
7. Portland & Pittsburgh & Berlin

**Comment by jonathandturner** [comment]
I'm a little hesitant about using this for something that might feel like advertising.  We left it pretty open ended saying "If you would like to be contacted by a member of the Rust Community or Core teams, please enter your email address."

I think it's probably okay to do a rare, big-announcement kind of email.  That said, I think the intent feels more like "if you'd like to learn more about Rust, contact us and we'll reach out to you."

Maybe in the next survey we can have a way for people to join a low-volume email list.

**Comment by carols10cents** [comment]
Turns out I don't have access to the google spreadsheet with the survey answers-- I can see the individual answers on the google form, but I can't tie the answers to the email question together with the conference question.

I've requested access through google docs but I'm not sure who that goes to... can either of yinz give me access @erickt @jonathandturner ? Or create a new spreadsheet with emails and the conference location question if you'd like to avoid spreading the whole thing around?

**Comment by carols10cents** [comment]
Text of the email I'm planning on sending, with appropriate edits/deletions made depending on which locations people expressed interest in: https://gist.github.com/carols10cents/fb7aa8ede31592351dcb3809de34ed82

**Comment by carols10cents** [comment]
WHEW emails all sent.
