### ISSUE TITLE
Brainstorm & price T-Shirt Quality Swag

### ISSUE THREAD

**Issue by edunham** [rust-community/team#53]
Mozilla outreach would like Rust stuff (in addition to stickers) to distribute as they promote the language. However, the current options we have for T-shirts are the year-out-of-date 1.0 shirts, and the Rustacean ones. 

T-shirts are subotimal swag because everyone already has so many, and it's hard to get the size and fit right. Other options we brainstormed include: 
- Coffee cups printed with Rust logo and command reference (edunham will mock these up)
- Multitools (probably too expensive, carries C++ swiss-army-knife connotations)
- Sewing/repair kits (OSBridge has given these out several times)
- Socks with Rust logo knitted into them
- Hats? 
- Some piece of safety equipment, such as protective gloves or safety goggles

**Comment by badboy** [comment]
Because I came across the tweet the other day:
https://twitter.com/hacks4pancakes/status/760584793629294592
https://twitter.com/wiredferret/status/760875060794040320

(these are just random ideas, not everything on those lists makes sense for us)

**Comment by carols10cents** [comment]
Kinda really want Rust socks now. 👍 to that! 👣

**Comment by brson** [comment]
I found a plain Rust logo T: https://teespring.com/shop/rust-programming-t-shirt#pid=369&cid=6512&sid=front

It's ... ok.

**Comment by edunham** [comment]
Also, iron-on decals/patches could allow people to put the Rust logo on a garment of their choosing

**Comment by edunham** [comment]
Additional ideas: 

* Apparently you can get https://sugru.com/ with a logo/brand on the packaging. 
* Plastic webcam covers seem to be popular at the moment, have room for a small logo, & play into the security theme of Rust
* Tiny notebooks -- you can get branded field notes journals that are high quality, useful for coders, and easy to ship

**Comment by stusmall** [comment]
I'd buy rust branded socks in a heartbeat.

**Comment by softprops** [comment]
Lego crab?

**Comment by frewsxcv** [comment]
For the record, Brian posted about this on the forums: 

https://users.rust-lang.org/t/all-the-rust-swag/7036

**Comment by jrichocean** [comment]
Mousepads?

**Comment by erickt** [comment]
Lets move this conversation to the [urlo thread](https://users.rust-lang.org/t/all-the-rust-swag/7036).
