### ISSUE TITLE
 2016-08-17 Community Team Meeting #55

### ISSUE THREAD

**Issue by skade** [rust-community/team#56]
Meeting at 4pm UTC on #rust-community on irc.mozilla.org. Last week's agenda.

Agenda:

* Mozilla being an unreliable community partner for non-Mozillians
* Update on the RustBridge shopathons
* bors checkin
- activate mozilla update (brson)

**Comment by badboy** [comment]
[Last week's agenda](https://github.com/rust-community/team/issues/54)

**Comment by carols10cents** [comment]
* I don't see edunham on https://www.rust-lang.org/en-US/team.html yet, and are we missing anyone else? I'd be happy to put together a PR but I want to make sure we have everyone.

**Comment by jonathandturner** [comment]
- Outreach to commercial Rust users (and potential commercial users)

**Comment by erickt** [comment]
@carols10cents: ack you're right! I just submitted a PR to add @edunham! (sorry about the delay @edunham!)
