### ISSUE TITLE
2016-08-24 Team Meeting

### ISSUE THREAD

**Issue by erickt** [rust-community/team#57]
Meeting at [4pm UTC](http://everytimezone.com/#2016-8-3,1680,cn3) on #rust-community on irc.mozilla.org. [Last week's agenda](https://github.com/rust-community/team/issues/56).

Agenda:
- [aelita](https://github.com/AelitaBot/aelita) vs homu vs bors vs [eeyore](https://github.com/eeyorebot/eeyore) (brson)
 - bors-a-thon
- rustbridge event happening at rustfest.eu
- Business outreach - @jonathandturner, @carols10cents, @brson 
- activate mozilla participation event update (brson)
- website for rust-community, rustbridge, and etc
- friend-of-the-forest
- orphanage

**Comment by locks** [comment]
@erickt can you add `eeyore` to the bot section of the discussion?

**Comment by erickt** [comment]
Summary:
* bots
 * https://github.com/rust-community/team/issues/58
 * @notriddle, @locks, and etc are going to talk about bots on #bors
 * No movement on bors-a-thon
* rustbridge
 * example [closing and survey from railsbridge](http://docs.railsbridge.org/workshop/closing#you_have_completed_railsbridge_38)
 * need volunteers to read through the [workshop materials](https://github.com/rust-community/rustbridge/tree/master/workshops)
* business outreach
 * @jonathandturner, @carols10cents, @Manishearth, and @brson have an outreach list
 * emailing surveyed people before the next meeting
* [mozilla participation event](https://discourse.mozilla-community.org/t/activate-mozilla-dive-into-rust/10073)
 * @brson will find someone to bring to the meeting
* @carols10cents is so on the nose of things she's going to build us the prettiest website we've ever seen and we'll be so happy
 * https://www.ruby-lang.org/en/community/
 * https://activate.mozilla.community/developer-engagement/rust-hack
 * http://www.railsbridge.org/
