### ISSUE TITLE
Community automation initiative tracking issue

### ISSUE THREAD

**Issue by bstrie** [rust-community/team#58]
There are various bots in-development looking to replace or complement homu. This would be a boon for the community at large, so we've taken an interest in helping the backers find resources for development (particularly community support). This issue exists to help community team members and potential contributors understand the lay of the land.

At the moment there are two projects that I know of: aelita and eeyore. I'd like to invite the people behind these projects to leave comments regarding their intended scope, and the ways that they would like the community team to be able to help out.

**Comment by carols10cents** [comment]
[Eeyore](https://github.com/eeyorebot/eeyore) is a project that @steveklabnik and I had grand ideas for but we never got it off the ground. It is meant as a bot that would allow repo admins to allow people to triage github issues without needing push permissions on the repo directly: the eeeyoretriage user would get the push permissions and keep track of people who had triage permissions, and if a triager asked eeyoretriage to add/remove/change labels, reopen/close issue, etc, eeyoretriage would do it for them.

The exact behavior and features are still very much up in the air-- [steve and I actually discovered that we were envisioning the workflow in very different ways!](https://github.com/eeyorebot/eeyore/issues/8#issuecomment-195806042)

I got stuck shaving some yaks-- hubcaps didn't (and still doesn't) have all the github api features eeyore would need, i upgraded some dependencies and fell down a rabbit hole of upgrading the url crate everywhere for everyone, etc.

I would love to have any help moving eeyore forward, as I think it would be super useful. I would love to have triagers help on repos of mine and I would love to help triage, say, crates.io, which is how eeyore got brought into this conversation :)

I've already added @locks, @booyaa, and @skade to the eeyorebot org (and they're already helping to get eeyore into a better state!), and I'm happy to add anyone else in the greater rust community who would like to help out in any capacity <3

**Comment by skade** [comment]
@carols10cents This issue has been lingering. Do you feel like we should we revisit this or shall we close it?

**Comment by carols10cents** [comment]
I just became aware that @notriddle is looking for moderators for https://github.com/bors-ng/bors-ng 's repo and mailing list, but that might be more of a question for the moderation team than community team.

In general, the issues mentioned here might be better for the infra team now?

Since we haven't really done much on this, and folks haven't been clamoring for our support, I think we can close this.
