### ISSUE TITLE
Community team website

### ISSUE THREAD

**Issue by carols10cents** [rust-community/team#59]
Rust community: What do they do? Do they do things? Let's find out!

Any help much appreciated! Let's discuss on this issue!
## Ideas for content for the website
- Meetups
- Community projects
- When our meetings are
- How you can get involved
## Sites for inspiration
- https://activate.mozilla.community/developer-engagement/rust-hack
- http://www.railsbridge.org/
- https://www.ruby-lang.org/en/community/
## Technical stuff
- Probably jekyll on gh pages
- Probably ugly/a default template unless someone helps me

**Comment by carols10cents** [comment]
@edunham has started a page with some things here: https://rust-community.github.io/resources/ but not all things! 

https://github.com/rust-community/resources

**Comment by edunham** [comment]
Partially addressed by https://github.com/rust-community/rust-community.github.io. I cargo culted the CSS from the main Rust site and added content by hand, which is super not ideal, but now we have a thing so people can asynchronously work on content, appearance, and a respectable build process.

**Comment by carols10cents** [comment]
* Document https://github.com/rust-unofficial

**Comment by edunham** [comment]
@carols10cents, I think the relevant repos list on https://rust-community.github.io/resources/, which is linked directly from the main page, plus https://github.com/rust-unofficial/about in that org, might be enough to address your point.

**Comment by marti1125** [comment]
Hi! how to I can help =D

**Comment by carols10cents** [comment]
> Hi! how to I can help =D

Hi @marti1125! How would you like to help? The website repo is at https://github.com/rust-community/rust-community.github.io and you can view the current site at https://rust-community.github.io/. 

We could use help with content -- Is there anything missing from that page that you would expect to be there? Did we cover everything listed here? Is it easy to find everything listed here on that site?

We could also use help with HTML/CSS; imo the paragraph that starts with "The Rust Community team is dedicated to..." should be wider so that it stretches over both columns below it. Also the font sizes in the nested `<ul>`s should get smaller (or at least stay the same) as the bullets indent, rather than larger as they do now. And anything else you see if you have an eye for design!

Thank you for your offer and sorry for the delay in getting back to you! ❤️

**Comment by skade** [comment]
Closing this here in favor of https://github.com/rust-community/rust-community.github.io/issues

**Comment by skade** [comment]
@marti1125 would you still want to lend a hand? <3

**Comment by marti1125** [comment]
Is there an issue where I could contribute?
