### ISSUE TITLE
Organize a community night during the Mozilla London work week

### ISSUE THREAD

**Issue by erickt** [rust-community/team#6]
A bunch of us will be in London 6/13th through the 17th for the next Mozilla All Hands work week. We should organize a community night for all the Europeans in the area.

@aturon: can you figure out what evening would be free for us to meet?

**Comment by aturon** [comment]
I can say it probably shouldn't be the 13th, since that's a "travel day" and people will be arriving at all kinds of times.

Otherwise, the overall schedule is determined by Mozilla as a whole, so I won't know the details until that's announced. But generally speaking, the evening events are optional, so if need be we can just set something up and skip out on the Mozilla stuff that night.

**Comment by Manishearth** [comment]
IIRC @jgraham and @SimonSapin used to organize the london meetups, so they can coordinate with the local community.

(Both should be there at the workweek too)

**Comment by booyaa** [comment]
if there's anything me or @vladimir-lu (we're the london meetup organisers/non-mozilla) can do to help out just let us know.

**Comment by Manishearth** [comment]
We should check back here one the Sched has come up and some of the meeting planning dust has settled.

**Comment by SimonSapin** [comment]
I’m told that the Mozilla London office will be in the middle of moving locations in June, so it’s not available as a venue.

**Comment by booyaa** [comment]
If the London office isn't available, could we approach the Skillsmatter team? They have a really nice venue not too far from Liverpool Street Station called [Code Node](https://skillsmatter.com/event-space). They are very receptive to hosting user group meetups, not sure how much they charge though.

**Comment by Manishearth** [comment]
Would it be possible to get a largish room at the All Hands location itself? I'm not sure how this works.

**Comment by larsbergstrom** [comment]
I can help make an official request to the admins and organizers if you can get me some numbers on:
- Attendance
- Date and times

In the past, we've been able to make one of the reserved hotel rooms available for after-hours meetings, but with the caveat that they usually don't have any service (water, snacks, cleanup in place).

**Comment by erickt** [comment]
@aturon: any word on the agenda for the week? I haven't been able to find any yet.

**Comment by aturon** [comment]
@erickt I haven't heard anything yet, but will ping somebody at Mozilla to try to learn more.

**Comment by booyaa** [comment]
We've still not announced our 6th meetup for June, if we wanted to "poach" one or some of your team members to do talks, would it better raise a separate issue? We're happy to conflate the two events, but I'm in the process of securing a spot at [SkilsMatter Code Node](https://skillsmatter.com/locations/264-skills-matter-codenode) facility because London Mozilla office is moving.

cc @vladimir-lu

**Comment by aturon** [comment]
We've got schedule information: we'll have the nights of Tues-Thur (June 14-16th) open from 6pm onward. If one of those nights works, we can definitely have some Rust core devs give a talk.

@booyaa I don't think anyone from the Mozilla Rust team is planning to be in London that early. See dates above.

**Comment by SimonSapin** [comment]
@aturon I had the same reaction as you at first, but I think that @booyaa means that it will be the 6th time there’s a Rust meetup in London, not the 6th of June.

**Comment by aturon** [comment]
@SimonSapin Ahha, yes, I did misread.

In any case, FWIW @alexcrichton is already planning a European tour prior to the workweek (in Germany and France), and he at least will have a slide deck ready :)

**Comment by vladimir-lu** [comment]
Does the 16th June work for you guys? I'm inclined to go with later on in the week as that seems to be when attendance is better.

**Comment by aturon** [comment]
Sure, 16th should be fine. I believe that @alexcrichton's planned slides are for an ~hour long talk -- @alexcrichton, want to post the abstract here?

**Comment by booyaa** [comment]
I'm fine with the 16th, trying to confirm the venue we're still aiming for the Skillsmatter's Code Node (near London Liverpool Street Station).

**Comment by alexcrichton** [comment]
Sure! Here's what I've got so far

> An exploration of the Rust project and community since the 1.0 stable release in May 2015 followed by a taste of what's to come from Rust in 2016. We'll take a look at incremental compilation in the compiler, a futures implementation for async I/O, and tooling updates especially around formatting and IDE support.

**Comment by booyaa** [comment]
Right unless anything goes horribly wrong we've got the Skillsmatter's venue CodeNode for the 16th of June 7PM onwards. I'll post the registration URL, we've just setup the meetup event: http://www.meetup.com/Rust-London-User-Group/events/231332388/

@alexcrichton - This sounds excellent, is there a title or tagline of the talk?

**Comment by alexcrichton** [comment]
@booyaa Sure! How about:

State of Rust 2015

**Comment by skade** [comment]
Work week is over. Closing
