### ISSUE TITLE
2016-08-31 Team Meeting

### ISSUE THREAD

**Issue by erickt** [rust-community/team#60]
Meeting at [4pm UTC](http://everytimezone.com/#2016-8-3,1680,cn3) on #rust-community on irc.mozilla.org. [Last week's agenda](https://github.com/rust-community/team/issues/57).

Agenda:
- [RustConf Booth](https://github.com/rust-community/team/issues/62)
- [RustConf Surveys](https://github.com/rust-community/team/issues/61) - @erickt
- RustBridge
- [Our bot overlords](https://github.com/rust-community/team/issues/58) - @locks / @notriddle / @carols10cents
 - bot-a-thon
- friends-of-the-forest - @brson 
- [community team website](https://github.com/rust-community/team/issues/59) - @carols10cents
- [business outreach]() - @jonathandturner
 - @jonathandturner said he'd try to mail companies by this meeting
- mozilla participation event update - @brson
 - @brson said he'd try to invite someone from mozilla reps to this meeting
- friend-of-the-forest
- orphanage

**Comment by skade** [comment]
Logs here: http://logs.glob.uno/?c=rust-community#c6536
