### ISSUE TITLE
2016 Rust Conference Surveys

### ISSUE THREAD

**Issue by erickt** [rust-community/team#61]
We got a couple conferences coming up. Sounds like a great opportunity to ask questions from our community about their experience. Also, this would also be a good opportunity to help guide the community towards working on various projects, so we should try to at least capture contact info to help point them at where they can start participating.

**Comment by johannhof** [comment]
Maybe also ask people who didn't attend why they didn't/couldn't attend. (Expensive, can't travel, no childcare, I {don't|only} like conferences on weekends, talk topics weren't interesting etc.)

**Comment by skade** [comment]
We have discussed this and think it is more worthwhile if the conferences run their own surveys if they want and we provide a writeup to the community team.

**Comment by carols10cents** [comment]
Leaving this open for us to revisit after Rust Belt Rust to see if we discover any reasons to run a conference-focused survey for the community team, perhaps to ask why people weren't able to attend any of the conferences, or if something comes up with all of the conferences that the community team would like to be able to do something about.

**Comment by skade** [comment]
Should we close this?

**Comment by carols10cents** [comment]
Yup
