### ISSUE TITLE
2016-09-07 Team Meeting

### ISSUE THREAD

**Issue by carols10cents** [rust-community/team#64]
Meeting at [4pm UTC](http://everytimezone.com/#2016-8-3,1680,cn3) on #rust-community on irc.mozilla.org. [Last week's agenda](https://github.com/rust-community/team/issues/60).

Agenda:

* RustConf Table volunteers
 * 8:30-9:45am Before Keynote - @erickt
 * 10:30-10:45am
 * 11:15-11:30am
 * 12-1:30pm Lunch - @edunham, @erickt
 * 2:45-3:00pm
 * 3:30-4:00pm
 * 4:30-4:45pm
 * 5:15-5:30pm
* Weigh in on 2017 planning  #72

**Comment by bstrie** [comment]
* Coordinate on corporate user outreach

**Comment by edunham** [comment]
* Brainstorm tl;dr summary of community team (https://github.com/rust-community/team/issues/69)

**Comment by skade** [comment]
This is still missing a link to the notes.

**Comment by carols10cents** [comment]
Minutes https://github.com/rust-community/team/blob/master/meeting-minutes/2016-09-07.txt
