### ISSUE TITLE
2016-09-14 Team Meeting

### ISSUE THREAD

**Issue by carols10cents** [rust-community/team#65]
Meeting at [4pm UTC](http://everytimezone.com/#2016-8-3,1680,cn3) on #rust-community on irc.mozilla.org. [Last week's agenda](https://github.com/rust-community/team/issues/64).

Agenda:

* Report on how the community table at RustConf went!
* How should we write up:
 * [Friends of the Forest](https://github.com/rust-community/team/issues/77)
 * [Looking for Contributors](https://github.com/rust-community/team/issues/74)
* RustFest checkin
* RustBridge
* https://rust-community.github.io/

**Comment by jonathandturner** [comment]
Update on Rust commercial outreach

**Comment by erickt** [comment]
Summary:

* @hannelita / @aepsil0n: need review or help on rustbridge?
* add friends of the forest to twir
* [Crate naming service](https://github.com/rust-community/team/issues/78)
* need to figure out how many stickers are needed at what event
* @hjr3 will try to give a rust talk at Harvey Mudd
* @jonathandturner should have an estimate at the end of the week on 
* need a description of the community: https://github.com/rust-community/team/issues/69
* [brainstorming 2017 milestones](https://public.etherpad-mozilla.org/p/rust-community-milestones-2017)

**Comment by hannelita** [comment]
Hi! Sorry, I've been away from the last 3 meetings but I can help on the workshops on Sunday.

**Comment by carols10cents** [comment]
Minutes https://github.com/rust-community/team/blob/master/meeting-minutes/2016-09-14.txt
