### ISSUE TITLE
Description of the community team for community page

### ISSUE THREAD

**Issue by skade** [rust-community/team#69]
Port https://internals.rust-lang.org/t/announcing-the-community-subteam/2248

to

https://github.com/rust-community/team/issues/59

:)

**Comment by edunham** [comment]
page is live now, https://rust-community.github.io/

turns out project pages have to be on the master branch, not gh-pages.

**Comment by edunham** [comment]
@erickt wrote, and I tweaked, an acceptable blurb: 

"The Rust Community team is dedicated to bringing new people into the Rust Programming Language's community, and helping established Rust communities thrive. "

If anyone sees room for improvement on this, just commit or PR it to the repo!
