### ISSUE TITLE
Weigh in on 2017 planning

### ISSUE THREAD

**Issue by aturon** [rust-community/team#72]
Hey Community team: just wanted to make sure you're aware of the [2017 planning process](https://internals.rust-lang.org/t/setting-our-vision-for-the-2017-cycle/3958/) that's gotten started. The original post highlighted some community issues (related to mentoring and diversity), but it'd be great to get some explicit commentary from your perspective!

**Comment by erickt** [comment]
We talked about this at the team meeting. We're going to take this opportunity to come up with a 2017 driving document like our [team announcement](https://internals.rust-lang.org/t/announcing-the-community-subteam/2248). One of the driving narratives might be centered around the whole idea of growing new communities. RustBridge naturally falls into that, as well as working on http://www.rustaceans.org, and figuring out how to encourage people to work on important projects. We'll start hashing this out at RustConf.

**Comment by skade** [comment]
2017 planning is over :). Looking forward to 2018!
