### ISSUE TITLE
Move nrc's docs projects to unofficial

### ISSUE THREAD

**Issue by nrc** [rust-community/team#73]
patterns: https://github.com/nrc/patterns
Rust for C++ programmers: https://github.com/nrc/r4cppp

There is interest in helping maintain the patterns repo, and it being somewhere more public and visible. I figured, may as well move r4cppp too.

No rush on this - I'm unlikely to do anything until next week because of Rustconf + travel

**Comment by skade** [comment]
@nrc I lost context of this. How does this involve the community team?

Also, if this happened or better for other channels, could you please close? Thanks! :)

**Comment by nrc** [comment]
>How does this involve the community team?

I think the community team run the rust-unoffical repo?

> Also, if this happened 

Patterns is moved. r4cppp is not, but hasn't seen much update recently, so probably doesn't matter.

**Comment by skade** [comment]
Ah, sorry, I mixed it up with the nursery in my Saturday rush.

Thanks :).
