### ISSUE TITLE
Publish cities of crate/project owners and production users who opt-in

### ISSUE THREAD

**Issue by edunham** [rust-community/team#75]
I just chatted with someone from the Seattle Rust meetup at RustConf, and we discussed that it would be useful to include city metadata on the list of projects seeking new contributors. That way, local meetups seeking people to give tutorials or talks could contact the project contributors, and the projects could extend their reach to potential new contributors. 

Alternately (I think an existing issue may capture this as well, but forget what repo it's on) it would be cool to extend Rustaceans to include a list of cities to which each person would consider travelling if they were invited to speak at a meetup.

**Comment by badboy** [comment]
Part of #12

**Comment by ashleygwilliams** [comment]
closing as this is well address in #12 i believe
