### ISSUE TITLE
Check community calendar events' validity every so often

### ISSUE THREAD

**Issue by edunham** [rust-community/team#76]
Community calendar has infinitely-recurring events for many meetups. 

Events link to EventBrite/Meetup.com pages, often, for additional data. 

Sometimes the EventBrite/Meetup/Whatever links are dead. We should have a process for noticing this; even if it's just exporting an agenda and manually checking them every quarter or so.

**Comment by skade** [comment]
It would be great if we had some kind of todo service.

**Comment by skade** [comment]
I went through the october events and they were all fine. The whole thing would be easier if people added a link to their meetup/whatever page to the calendar entry.

**Comment by ashleygwilliams** [comment]
this is related to #90 and i think a duplicate, i am going to close, and we can be sure this is covered when this is brought up in the next meeting (i've already marked #90 as an agenda item)
