### ISSUE TITLE
Friend-Of-The-Forest nominations from RustConf ("Who is awesome in your community?")

### ISSUE THREAD

**Issue by edunham** [rust-community/team#77]
Apologies in advance for any misspellings, typos, pings, mis-pings, etc. Attempting to type verbatim what's on the whiteboard, to get it in text rather than just a photo.

* dtolnay+oli_obk_serde - took over maintence _@erickt
* Answered my too many questions: @seanmonstar
* @phildwwes for racer
* @mitsuhiko for @redis
* serde team (dblnay, oli_obk, @erickt)
* @athemathmo for rusty_machine
* @carllerche for mio/tokio
* @killercup for keeping diesel running
* @dikaiosune - rusty-dash
* @nasa42 and @llogiq - This Week In Rust
* @WindowsBunny - being the fuzziest bunny +1 +1 (ed: the +1's are in different pens)
* @eddyb - for knowing everything about rust
* @chriskrycho for New Rustacean
* @steveklabnik, Rust documentation superhero
* carllerche, eternaleye, staticassert
* Matthias Beyer http://beyermatthias.de
* llogiq, manishearth

**Comment by hjr3** [comment]
I didn't put it on the whiteboard, but I would like to nominate @illegalprime for his work on https://github.com/cyderize/rust-websocket

Also, here is the photo:
![rust-community-white-board](https://cloud.githubusercontent.com/assets/33318/18415663/1bf146fc-77af-11e6-8dc0-ebe7520bd187.jpg)

**Comment by illegalprime** [comment]
Thank you! Although it's @cyderize's project, he's done a lot of work toward it.

**Comment by nrc** [comment]
I'd like to nominate @Mark-Simulacrum for awesome work on the compiler perf website

**Comment by frewsxcv** [comment]
@sfackler and @briansmith for enhancing the crypto/security story for Rust. Their efforts have made running Rust in production code much more feasible.

sfackler: [rust-openssl](https://github.com/sfackler/rust-openssl), [rust-security-framework](https://github.com/sfackler/rust-security-framework),  (significant contributions to) [schannel-rs](https://github.com/steffengy/schannel-rs), [rust-native-tls](https://github.com/sfackler/rust-native-tls)

briansmith: [*ring*](https://github.com/briansmith/ring), [webpki](https://github.com/briansmith/webpki)

**Comment by erickt** [comment]
Rough draft up at https://github.com/erickt/this-week-in-rust/blob/fotf/drafts/2016-09-20-this-week-in-rust.md#friends-of-the-forest. How's it look?

**Comment by sfackler** [comment]
Serde folks are up there twice :P

**Comment by skade** [comment]
I'm a bit weirded out that Friends of the Forest seems to attract lots of mentions of people that have contributions to other code, while the intention was definitely to highlight different contributions.

**Comment by chriskrycho** [comment]
@skade, that's actually not surprising in a lot of ways: many people contribute not only to the core but to other parts of the community as well, and specifically many of the people who are not core team members themselves but contribute actively to the language do so precisely because they're highly engaged developers in other parts of the ecosystem and have specific needs of the language.

You'll note that there are also a number of people on the list (like me) who have contributed basically *zero* code to the Rust ecosystem, so it's still doing what it should in that regard.

The other factor is newness; as people see this and become more aware of it over time, you'll see more and more people pointing out others who contribute in their own ways (hosting meet ups, etc.).

**Comment by skade** [comment]
@chriskrycho I'm aware of the dynamics and this shows gaps in communication. People not doing visible work are also not appreciated by such a public list, which shows we are bad at communicating what they do.

**Comment by erickt** [comment]
@skade: I see friends-of-the-forest as being an avenue where people can call out special contributions in any way people think was outstanding, just like you mentioned in #36 way back in June. For me, I've had some wonderful help with serde, but if someone helps someone out with a particularly tricky bit of lifetime magic, I hope they'd get nominated here. I'm also hoping we'll get submissions with more content than what could fit on a whiteboard to really go into detail about what was so awesome.

**Comment by llogiq** [comment]
I'd like to ninate @Veedrac for his awesome contributions to various performance-related endeavors.

**Comment by erickt** [comment]
@llogiq: [submitted](https://github.com/cmr/this-week-in-rust/pull/318), thanks!

**Comment by badboy** [comment]
It's published.
