### ISSUE TITLE
Blog post wanted list

### ISSUE THREAD

**Issue by skade** [rust-community/team#8]
@Manishearth and I came up with an idea on #rust-community: why not have a "blog post wanted" list with a set of topics which everyone with some time on their hand can write content for the rust blog?

My first idea was for example "How to get started on Windows?" (most FOSS software is just crappy on Windows, we should better propagate that we consider it a first class citizen)

**Comment by Manishearth** [comment]
- "String types in Rust"
 -  "How to reason about memory in Rust" (intros the stack and the heap and how this works with different Rust pointers and mechanisms for non-C++ folks)

**Comment by steveklabnik** [comment]
Yes, I've been pushing for more blogging on the official blog, so this is a
great idea for sure.

On Sun, Mar 20, 2016 at 1:58 PM, Manish Goregaokar <notifications@github.com

**Comment by erickt** [comment]
* "How to organize a Rust Meetup" - I get that one a lot.

**Comment by AndrewBrinker** [comment]
@Manishearth: No idea if this covers all you'd hope for it to cover, but I've just published a [blog post on Rust's string types](http://andrewbrinker.github.io/blog/2016/03/27/string-types-in-rust/). I am happy to update it based on any feedback people have.

**Comment by Manishearth** [comment]
@AndrewBrinker I was looking for something for newbies, more of, especially those without an understanding of the stack.

I'm planning a blog post series that teaches non-C++ folks about the stack and the heap from a rust point of view and goes on to deal with strings and why the borrow checker matters.

**Comment by Manishearth** [comment]
Actually, this is pretty ok for newbies. The jargon density got me at first, but it seems to explain things nicely. Thanks!

I'll still end up doing that blog series though :smile: 

The other day I was chatting with a Rust enthusiast coming from C# and I spent some time explaining String vs str and everything on a blackboard, and during the journey I realized how much of this stuff (understanding of the stack/heap and later in the discussion, the cache) we take for granted. The book tries to avoid that, but I want to attempt to do it even more explicitly and see if I can _teach_ these concepts through rust.

**Comment by AndrewBrinker** [comment]
Glad you like it! Jargon density is always a tough thing to handle. For this post I wanted to assume some familiarity with what the stack and heap are, but be very explicit about what ends up where, without getting bogged down in minutiae.

Also, you should absolutely still do the series! The Rust community can only benefit from more quality writing about the language.

**Comment by skade** [comment]
This would also fit a TODO list great.

**Comment by ashleygwilliams** [comment]
i would like to bring this topic back up at the next meeting as there is some neat work around the rust roadmap that i think we could do good work soliciting blog posts for, i'll be discussing it at the next meeting.

**Comment by ashleygwilliams** [comment]
given that we'll be kicking off our first blog experiment (https://github.com/rust-lang/blog.rust-lang.org/blob/c57e9a4713e70d861026485aa6eb7deef594eda5/_posts/2017-12-30-new-years-rust-a-call-for-community-blogposts.md) tomorrow for the rust roadmap, i think we can close this now- we'll open new issues as we have new themes to solicit blog posts for :)
