### ISSUE TITLE
Meetup starter kit

### ISSUE THREAD

**Issue by carols10cents** [rust-community/team#81]
We mentioned that creating a meetup starter kit would be something useful we could do. What should be in said kit? Is this a physical kit, virtual kit, or both?

Virtual:

- Link to https://github.com/ctjhoa/rust-learning/ that has some slides to use for intro talks, learning resources to use during meetups
- Ideas for activities to do during meetups
- Instructions on getting your event on the community calendar and your group on https://www.rust-lang.org/en-US/user-groups.html

Physical:

- Stickers

What else?

**Comment by skade** [comment]
* A guide on how to do outreach and find people
* Info on how to keep you group cool and likeable

**Comment by skade** [comment]
#4 is a copy of this issue, can one be closed?

**Comment by carols10cents** [comment]
Oops. I like the thought of a "kit"; i'll move the items from here to that issue and change that issue's title.
