### ISSUE TITLE
Document the community teams work in 2016

### ISSUE THREAD

**Issue by skade** [rust-community/team#83]
We should document the community teams work for 2016, maybe in the form of a blog post.

This supersedes #5

**Comment by erickt** [comment]
I've started to sketch out a summary in the [milestones](https://public.etherpad-mozilla.org/p/rust-community-milestones-2017) etherpad. Anyone, please feel free to flesh it out more.

**Comment by skade** [comment]
Can the whole @rust-community/community-team please give me their three favourite things _they_ were involved in (be proud of your stuff!).

Just give me a sentence on it, I will approach you when I need details.

**Comment by carols10cents** [comment]
1. I enjoyed putting on Rust Belt Rust and bringing together people interested in Rust in a Rust Belt city!
2. Holding the 2nd RustBridge event ever was amazing, not only did the attendees learn Rust, but I learned things from the attendees as well, like how similar Rust and Scala are!
3. I helped with the Rust Community survey and a little bit of the corporate user followup; we found out a lot of interesting things about what's awesome and not so awesome about Rust, and I'm excited to help with that in the future.

**Comment by Manishearth** [comment]
- Underhanded Rust! Was mostly @erickt but it was fun being a part of it
 - Being involved in prod user syncups. Loved hearing what worked/didn't work. Many prod users had great things to say which felt nice.
 - rustconf speaker selection (was on the wrong continent to help out much in the rest of the planning)

**Comment by skade** [comment]
2016 is over :). Happily looking forward to 2017s writeup!
