### ISSUE TITLE
Official youtube channel

### ISSUE THREAD

**Issue by skade** [rust-community/team#84]
Hi,

I opened an official youtube channel to have a venue where we can publish and republish video material from our conferences.

The channel is https://www.youtube.com/channel/UCaYhcUwRBNscFNUKTjgPFiA.

It also has an associated twitter account: https://twitter.com/rustvideos that tweets out additions to playlists.

I have currently set up a StrangeLoop 2016 playlist and a RustFest 2016 playlist for upcoming videos.

Missing things are:
- [x] Somehow Google thinks lets the twitter account tweet in German
- [x] Would someone be willing to create a Facebook page for easy sharing (Do we have mods for that)
- [x] Google+ anyone? :trollface: 

Also, @wifelette, would it be possible to host RustConf videos there?

Best,
Florian

P.S.: Credits: the idea of a unified channel is from https://medium.com/@cramforce/best-practices-for-publishing-conference-videos-5b85d84bb7fb#.pcwk0e869, and taken to a higher level.

**Comment by skade** [comment]
I changed the name of the StrangeLoop Playlist to "Other conferences 2016", as most of them will only have one or two talks.

**Comment by skade** [comment]
I also added a couple of channels for the last years. If you come across a good video on youtube, please switch your account to the Rust account and click "add to playlist".

I also disabled advertisement and advertisement based on user interest.

**Comment by skade** [comment]
We have a G+ page. Somewhere.

**Comment by skade** [comment]
Let's announce that later.

**Comment by skade** [comment]
There's a moderation queue setting for Youtube videos, shall we use that?

**Comment by skade** [comment]
The channel is now configured for having everything possible, including community-contributed captions, go to a moderation queue.

**Comment by erickt** [comment]
@skade: thanks for setting this up. What else needs to get done?

**Comment by skade** [comment]
@erickt a PR to the rust-lang website to claim ownership, and getting a vanity URL once we are eligible (channel needs to be 30 days old for that)

**Comment by wifelette** [comment]
Delayed reaction, apologies, been traveling and swamped!

The videos are being hosted on the Confreaks channel, which has 3k+ tech conf videos and 23k subscribers—so a super valuable and qualified audience to be able to have the Rust content pushed out to :) I was thinking y'all could make a playlist on this new Rust account and have that be the place the community is pointed at for the videos, if you want to start building up an audience here. Not sure what the plans are RE: publicizing the videos, but I imagine you'll tweet about them from the official Rust and RustConf accounts, so we can be sure the right links go out.

Congrats on putting this together!

**Comment by frewsxcv** [comment]
> getting a vanity URL once we are eligible (channel needs to be 30 days old for that)

Presumably 30 days have passed so a vanity URL can be registered for the channel.

**Comment by erickt** [comment]
It looks like someone set us up with the https://www.youtube.com/c/RustVideos URL.

**Comment by badboy** [comment]
Channel exist, Videos get uploaded/playlisted.
