### ISSUE TITLE
Slack channel open issues

### ISSUE THREAD

**Issue by jonathandturner** [rust-community/team#87]
From https://github.com/rust-community/team/issues/80#issuecomment-248335366

Currently open issues around creating a Slack channel:
- Should it be official or unofficial (note: /r/rust is unofficial, as one example)
- Do we need to grow the moderation team to help cover Slack?
- Can we ban/kick/mute/ignore people on Slack?
- General worry about having too many forums/fragmentation (eg, there's a gitter, though not sure how many of us are on it regularly)
- Is an IRC-to-Slack bridge required?

**Comment by carols10cents** [comment]
The stakeholders who should weigh in on the decision to open a slack channel include...?

- Core team (they have the authority to declare something official or unofficial and to grow the moderation team)
- Moderation team (do they have time to and want to moderate slack, do they need more members)
- Community team (is slack a venue that we want to be part of the rust community in an official or unofficial capacity)

Anyone else?

**Comment by Manishearth** [comment]
cc @rust-lang/mods

My personal recommendation wrt the moderation team stuff is to draft in additional slack mods, similar to how IRC is moderated with a combination of folks on the mod team and folks with op powers.

**Comment by aturon** [comment]
Note that it doesn't seem to work to cc the rust-lang team aliases, sadly...

FWIW, if the channel is unofficial, I don't see forum sprawl as being much of an issue -- especially given that, AIUI, there already exist unofficial slack channels? But then, OTOH, it's unclear what the community team's role would even be for such a channel?

In general the community team hasn't yet used the RFC process for reaching community-wide decisions. This issue is probably too small to warrant a full RFC, but it's worth thinking about. If not an RFC, it'd be good to advertise the question in *some* broad way before reaching a final decision.

**Comment by booyaa** [comment]
i'd be happy to help out modding the slack channel, could do guidance on what my remit is. also if the irc gateway can be enabled, i can monitoring between 7am-7pm (UTC+1)

**Comment by skade** [comment]
@aturon Well, the discussion of the community teams role here was also part of the last minutes.

I see the community teams role as such: we can make the suggestions and maybe try to encourage more people to take up a moderating job, but we can neither ask the moderating team to take that over nor set up the stuff ourselves.

Considering that the initiative for this came from core team members, we're more in reactive mode here, currently, trying to steer that into _some_ form of usable discussion.

I'm still not fully convinced the RFC process is a good way of doing things for most things community, but I agree that a more structured way of putting things up for discussion would help. I recently tried to advertise this bug tracker a bit more and we had some people taking part, e.g. by asking for a Facebook community.

**Comment by carols10cents** [comment]
Email of @jonathandturner's sent yesterday to rust-community, reposted here with permission:

>
> It seems like the thread has calmed down, so it seems like a good point to put a strawman together and see if we can address what people have mentioned.  If I'm missing anything, please let me know.
> 
> * Should it be official or unofficial (note: /r/rust is unofficial, as one example)
> 
> It sounds like the leaning here is "unofficial", which is fine, so long as people can still find it and we're okay with advertising it (so that people can find and use it over the other Slacks also called rustlang)
> 
> * Do we need to grow the moderation team to help cover Slack?
> 
> Manish and others said they'd be willing to help moderate, so we may be able to cover it with what we have.  If we need to grow, the moderation team will know and we can find the resources.
> 
> * Can we ban/kick/mute/ignore people on Slack?
> 
> It sounds like "yes, sort of": https://get.slack.help/hc/en-us/articles/201898668-Remove-someone-from-a-channel
> 
> Moderators, is this sufficient?
> 
> * General worry about having too many forums/fragmentation (eg, there's a gitter, though not sure how many of us are on it regularly)
> 
> This is a natural fear, though I suspect we won't know until we try.  Once we get a better understanding, we can adjust from there.  If we want, we could message out that the Slack thing is something we're going to try for 30 days and then evaluate.
> 
> * Is an IRC-to-Slack bridge required?
> 
> This is another one that I don't think we'll know until we try it.  If, say after a 30-day trial period, we find our attention is too scattered and the splintering is too costly, we can invest in possible bridging solutions.
> 
> * Carol mentions making sure all the stackholders could weigh in.  I think everyone on this thread (core, community, and mods) should be good coverage.
> 
> Are there any outstanding questions I missed?
> 
> 
> So, from the above, the strawman of the idea is:
> 
> * Unofficial, but publically-known so people can find it
> * Limited trial period, after which we evaluate if we want to continue it, and if we do, what kind of tools and resources are required.  I said 30 days, but that was just the first number that came to mind
> * Mod team will moderate
> 
> 
> With the above, I'm hoping we can work through the straw man and remaining questions and then make a call with a clear "no" or clear "yes".

**Comment by jonathandturner** [comment]
Opened URLO thread here: https://users.rust-lang.org/t/a-possible-rust-slack-channel/7433

**Comment by skade** [comment]
Closing because of relevant RFC and URLO discussion.
