### ISSUE TITLE
2016-09-28 Community Team Meeting

### ISSUE THREAD

**Issue by bstrie** [rust-community/team#89]
* check in on [actionables from prior meeting](https://github.com/rust-community/team/issues/80#issuecomment-248684846)
* Rust Belt Rust (@erickt)
* [Friends-of-the-Forest](https://github.com/cmr/this-week-in-rust/pull/318) (@erickt, #77, [nominations](https://users.rust-lang.org/t/twir-friends-of-the-forest/7295))

Carried over from prior agenda (#80):

* find a way to make regular tasks visible (@skade, #90 )
* [meetup starter kit](https://github.com/rust-community/team/issues/4) (@carols10cents)
* bors (@locks)
* meetingbot (keep moving this item towards the end because @booyaa won't join till 4:20PM UTC)

**Comment by carols10cents** [comment]
@skade is "find a way to make regular tasks visible" the same as #83 or are they different? If they are different, could you start a new issue so that we could have some async discussion before the next meeting?

**Comment by skade** [comment]
@carols10cents It's referring to https://github.com/rust-community/team/issues/76#issuecomment-248279505

I'll create an issue.

**Comment by jonathandturner** [comment]
* Slack channel
* Digital Ocean hacktoberfest: https://twitter.com/digitalocean/status/780905259191377920

**Comment by erickt** [comment]
Summary:

* @skade: youtube channel created: https://www.youtube.com/channel/UCaYhcUwRBNscFNUKTjgPFiA. vanity url can be created in 30 days
* @skade: no progress yet on herding various social media rust properties yet
* slack:
 * what if we decide to not go forward?
 * could setup a slack bot to forward people to supported channels
 * @jonathandturner: could just close it down

action items:
* document youtube submission process: https://public.etherpad-mozilla.org/p/rust-community
* upload air mozilla videos: https://github.com/rust-community/team/issues/93
* @jonathandturner will post the slack conversation to urlo
* @jonathandturner will reach out to digital ocean about getting rust projects into hacktoberfest
* @erickt will convert https://github.com/rust-community/team/issues/74 into a page on rust-community.github.io
* everyone needs to help watch the friends of the forest nominations: https://users.rust-lang.org/t/twir-friends-of-the-forest/7295
* get someone to write up a fotf for leah and tilde
* @brson will sync with locks and the aelitabot
* @badboy may look into setting up irc bridge that talks to slack

**Comment by jonathandturner** [comment]
I've added the URLO thread: https://users.rust-lang.org/t/a-possible-rust-slack-channel/7433

I've also reached out to digital ocean about hacktoberfest
