### ISSUE TITLE
Gitter channel open issues

### ISSUE THREAD

**Issue by carols10cents** [rust-community/team#91]
[Gitter channels for rust already exist](https://medium.freecodecamp.com/best-gitter-channels-on-rust-ad8f5f73b5a2#.y2t1o6o5m) and that blog post was described as "Best Rust community channels on Gitter" when [it was posted on reddit](https://www.reddit.com/r/rust/comments/53ifzx/best_rust_community_channels_on_gitter/), so presumably we have some of the same questions about gitter [as we do about slack](https://github.com/rust-community/team/issues/87):
- Do we want this to be official or unofficial? Are we making the distinction clear to people who use the service?
- Are there moderators on gitter? Can people report to moderators on gitter, can moderators ban/kick/mute/ignore people?
- Does the moderation team need to be more involved with gitter, and do they have the time to do so?
- There are library-specific channels on gitter in that post that people see as being part of "rust community channels"-- do we have any responsibility for those?

**Comment by brson** [comment]
There are no mods in this channel as far as I can tell. There's an [open PR](https://github.com/rust-lang/rust-www/pull/529) to add the gitter to the website.

I was quite surprised that this communication channel exists and appears to be endorsed by the Rust project.

**Comment by brson** [comment]
The thing that bothers me about using gitter as a "beginner destination", as suggested in the www PR, is that the gitter channel is a single channel, linked to the address of the github repo; there is one such channel, so why should that be "the beginner channel"? There are many things that a `rust-lang/rust` channel could be for.

**Comment by skade** [comment]
Is it endorsed by the Rust project? Gitters model is that there is automatically a channel for any project.

**Comment by brson** [comment]
It is not endorsed by Rust today. I did not know it existed until last week, and I suspect the same is true for many people.

**Comment by brson** [comment]
I also don't think gitter automatically creates rooms for any project - somebody with access has to make them.

**Comment by brson** [comment]
It does look like we could create a new room with an arbitrary name, so if we wanted we could create a `rust-lang/beginners` room.

**Comment by mhsjlw** [comment]
You could create a room for `rust-lang/beginners` if you wanted to. You could even make private channels just for maintainers, mods etc. Yes there is opping and banning on Gitter.

**Comment by skade** [comment]
Ah, sorry, I was pretty sure they did that at the beginning. Well, same here, we can adopt things if we can name someone in charge.

**Comment by BurntSushi** [comment]
I hadn't even heard of "gitter" itself until recently, and I'm also quite surprised to see over a thousand people there. I'll start idling there for its sheer size alone.

(I'm not really a fan of having all of these different channels for chat, but it seems futile to fight it.)

**Comment by jonathandturner** [comment]
I've been sitting in the gitter today to see what it's like.  So far I see 1000 people registered in it, but only a dozen or so talking today.  Mostly beginners helping beginners, which is problematic.

At the very least it wouldn't hurt for a few more advanced Rust people in there answering questions.

**Comment by mhsjlw** [comment]
@jonathandturner we've got to get the word out first, hence https://github.com/rust-lang/rust-www/pull/529 :smile:

**Comment by mkpankov** [comment]
We're using Gitter in our Russian community. I can share some experiences.

> Are there moderators on gitter? Can people report to moderators on gitter, can moderators ban/kick/mute/ignore people?

There are no moderators, except the owner of the room. Owner is the person who created it. It's probably transferrable, but only by contacting support - no interface. Owner can ban people and can remove them from the room.

This is starting to be problematic even for us, and we're under 300 people.

However, I've found [open issue](https://github.com/gitterHQ/gitter/issues/1079#issuecomment-173292853) on Gitter and it states organization rooms give admin access to all of organization members. Can't confirm though - we didn't use this.

**Comment by mhsjlw** [comment]
Can confirm this. If you're part of an organization on GitHub in the Gitter chat you get admin.

**Comment by booyaa** [comment]
Newly announced [mod tools](https://gitter.im/gitterHQ/topics/topic/5809efc7b17b667961e0b359/moderation-tools).

**Comment by skade** [comment]
@rust-community/community-team I feel like this discussion has move towards last years RFC. I feel like it can be closed _here_. Does anyone disagree?

(This does not imply any stance to the issue. Personally, I think the topic should be revisited regularly)

**Comment by ashleygwilliams** [comment]
@skade i'm closing this, i think your intuitions are correct. if we revisit this topic in the future (i think we might) we can either reopen this or start a new issue.
