### ISSUE TITLE
Upload air mozilla rust videos to youtube

### ISSUE THREAD

**Issue by erickt** [rust-community/team#93]
There's a lot of content on air.mozilla we should get on our youtube channel.

**Comment by skade** [comment]
Shall we just download the videos or is there a way to get them in bulk from the source?

**Comment by skade** [comment]
Hm, there seems to be no possibility to get a full feed of a channel from air.mozilla.org :(

**Comment by skade** [comment]
The archives are available through the roku feed... https://air.mozilla.org/roku/channel/rust.xml

**Comment by skade** [comment]
This is done. Leaving open until I documented the used piece of software.

**Comment by skade** [comment]
This has an issue: we uploaded the many low versions of the videos. Also, word on the street is that Mozilla Air is on the way out, so I don't quite know how to go forward with that.

I am considering to not add further air videos and encourage people to upload the videos themselves.

**Comment by skade** [comment]
Closing. It's done in general, any changes to this should go through a new ticket.

**Comment by learninggrowing** [comment]
I use Allavsoft to batch download from air mozilla rust videos
http://www.allavsoft.com/how-to/download-air-mozilla-videos.html
