### ISSUE TITLE
Rust for University & College Students

### ISSUE THREAD

**Issue by LucyeoH** [rust-community/team#94]
Hi Rust Community Team,

My name is Lucy from the Participation Team we just started a new program to try and get Computer Science students at Universities and College all over the world participating with open source and contributing to Mozilla's mission. 

The Club model assumes that groups of CS students will meet on a semi-regular basis to run activities, build things, and learn together. Our website is: http://campus.mozilla.community/.

As the program is new we're trying to get a roster of awesome activities that will motivate CS students to start and attend Campus Clubs. I suspect that Rust is an awesome way for students to engage with an exciting new technology while developing new skills that traditional CS educations don't include. 

I would love to design a Rust activity specifically aimed at students in the Clubs environment (meeting regularly and working in teams to learn and build together). 

We currently have [this activity](https://mozilla.github.io/activate.mozilla.community/developer-engagement/rust-hack/). But I don't think it's optimal in the way it describes why Students should get involved, or how to work it into a regular Club program. 

**The Ask: Can you help me improve our Rust activity (or build a series of activities) so that it is a genuinely appealing offering to CS students with a passion for the open web all around the world?** 

Note: We already have over 250 campuses registered!

**Comment by Manishearth** [comment]
(This is on the agenda for today's meeting, sorry for dropping the ball here!)

**Comment by brson** [comment]
Sorry it's been taking so long here @LucyeoH. This sounds like a great opportunity for Rust, and you're right that Rust is an exciting topic for students.

One of the most notable aspects of Rust's development is that its developers are so young. It's really striking how much of Rust has been built by ambitious students in their free time. It's a great opportunity for students to get into open source development in a supportive environment, get public, real world experience working on a large-scale software project, create useful GitHub cred and early resume-building material, and learn some serious CS skills. A number of smart people have created a promising start to their career by making a name for themselves in Rust. I'm really excited to see the affect 10 years from now of Rust seeding the engineering world with the Rusty worldview.

I'll schedule sometime to brainstorm about this activity and how to engage students to contribute to Rust at such a large scale. Feel free to ping me by email about this as well if you like.

**Comment by brson** [comment]
cc @edunham @jonathandturner

**Comment by badboy** [comment]
oh, we should have posted an update here as well. @brson: Lucy joined the meeting last week and we discussed it. See the full minutes here: https://github.com/rust-community/team/commit/48a8fce553befbaa692e80857c4982f3663c2731#diff-a70e5b9816c21c3438b64621e8d1766fR26 – We pointed her to existing material

**Comment by edunham** [comment]
@LucyeoH Does the material that we provided in the meeting in October meet your needs, or are there other things you'd like help with in order to consider this issue resolved?

**Comment by bacharakis** [comment]
Hi there, you can consider this issue resolved but we will definitely come back with our proposal for feedback! What is the best way to do that? Paste it as an issue or drop you a line and schedule a meeting?

**Comment by badboy** [comment]
Open an issue to ask for feedback. We can then put it on the agenda for the next upcoming meeting and as always you are happy to join that meeting to discuss it further.
