### ISSUE TITLE
novemb.rs Community code sprint

### ISSUE THREAD

**Issue by skade** [rust-community/team#95]
Hi,

bringing this from the emails towards our issue tracker. Mozilla DevRel asked if we would like to run another set of European events. We threw around the idea of a distributed code sprint at Berlin/Paris/London and maybe other locations, where we use a weekend to hack on things.

To gauge availability of local organisers and sync up, I created this doodle:

http://doodle.com/poll/pswr9esd7qxabndg

Feel free to enter your available weekends, please don't forget to put in where you are.

Best,
Florian

**Comment by SimonSapin** [comment]
CC @pnkfelix @nox @nical

**Comment by badboy** [comment]
cc @killercup @colin-kiegel @florob

**Comment by erickt** [comment]
cc @booyaa / @johannhof

**Comment by johannhof** [comment]
So I think late-ish November fits much better for me and the Berlin Mozilla office. I really like the idea of a code sprint (or another doc sprint?), but we could also aim for a day one beginner workshop (another RustBridge iteration?)/day two code sprint event...

**Comment by skade** [comment]
@johannhof I would avoid too much planning, it's towards the end of the year. If people want to run such a thing... sure!

In general, let's find a date first and then discuss program with the people that take part.

**Comment by badboy** [comment]
So we over here in Cologne (@Rustaceans/organizers-cologne) would like to join in and open doors for some hacking days if it happens.

**Comment by skade** [comment]
@booyaa has no time except the weekend at the beginning of November (which would probably lead to an extreme rush). Would there be anyone else available in London? (e.g. Victor?)

**Comment by skade** [comment]
This is a bit unfortunate, but I would prefer the 19/20 November. That gives us about a month of planning and time to get other people on board.

**Comment by skade** [comment]
Okay, in the absence of other opinions, I'll decide on 19/20th :). Please complain until tonight, 17:00.

**Comment by booyaa** [comment]
@skade - Would it be possible to contribute a few hours remotely? I'd still like to help out.

**Comment by skade** [comment]
Sure, I'd like to add a remote option.

**Comment by skade** [comment]
Okay, due to an issue with the node community having their fun at the Mozilla place in Paris on the 19th, I suggest we shift this to 26/27th.

**Comment by skade** [comment]
Thinking about this a little more, this is more about being in the same timezone then being in Europe. I would like to also find people south of Europe, mostly African countries to run satellite event.s

**Comment by skade** [comment]
News is just in that the Paris office has a WiFi upgrade on the 26/27... Either we find another location in Paris or just use the Paris office on the Sunday. Any takers?

Also, accepting GIFs to illustrate "please wait while this office upgrades".

**Comment by edunham** [comment]
I'd be happy to skew my sleep schedule to make sure I'm around during whatever hours you decide if sprint tasks will include infra. Could you send me (edunham@mozilla.com) a calendar invite with the correct times and timezone once you get that finalized, so I can make sure to be around?

**Comment by skade** [comment]
@edunham I will happily do so, thanks! <3

**Comment by booyaa** [comment]
Any ideas how the teleworkers can stay in touch i.e. email, irc, hangout? 

I'd prefer hangout so i can hear other people speaking, I don't know what the actual experience is like i.e. does it work?

Have we done remote participants before?

**Comment by skade** [comment]
@booyaa Currently, IRC would be one angle, others are unclear. Maybe someone wants to assist with these things? :)

In general, I would guess people working on the same topic can also choose what they want by themselves.
